### PR TITLE
Fixed Level Mode Sliders Return to zero

### PR DESCRIPTION
**Pull request by mgubisch**
Fixed
http://www.qlcplus.org/forum/viewtopic.php?f=29&p=45442#p45442

Problem was that slider in monitor modes first reads the value from the universe before appling its own value.
Now with first appling slider settings and monitoring afterwards everything works as expected

### CODE REVIEW

**Comment by mgubisch** [comment]
WTF git, why is my second commit also in the pull request :(
Only the commit from yesterday should be here....

**Comment by janosvitok** [comment]
Matthias, the commit appears here because all commits that you push to a branch for which you've created PR are added to the PR.

**Comment by mgubisch** [comment]
Hmm thats bad, because the current version shouldn be in the official repository.
Is it possible for you just to merge the first commit? otherwise i will close this pull request and merge the commit to a new branch for a new request.

**Comment by mcallegari** [comment]
@mgubisch  We don't merge anything until there is an ongoing discussion in the forum and until we test the change

**Comment by mgubisch** [comment]
Well there is a discussion on the Forum
The actual version of my levelmode slider is far from being ready for the official Repo 
Closed this Request for Now

**Comment by mgubisch** [comment]
Well there is a discussion on the Forum
But the actual version of my levelmode slider is far from being ready for the official Repo 
Closed this Request for Now

**Pull request closed without merging**
