### PR TITLE
Require capabilities in fixture.xsd

### PR DESCRIPTION
**Pull request by fxedel**
The php fixture validator (L129) checks if there are capabilities present:
```php
if (!isset($channel->Capability))
{
    print "ERROR: channel &lt;".$origName."&gt; has no capabilities. Please define at least one, with a meaningful description<br>";
    $error++;
}
```
If this check is right, I guess the schema can also demand a minimum of 1 capability.

### CODE REVIEW

**Comment by fxedel** [comment]
Maybe we can also set `maxOccurs` to 256 as it isn't possible to create more capabilities in a 0-255 scope.

**Comment by janosvitok** [comment]
I agree with this change, I've added the proposed change to your branch. I prefer that we fix the fixtures on the branch before committing the change to schema.

These are the fixtures that do not validate (35):

- [ ] American-DJ-Accu-UFO.qxf
- [ ] Briteq-BT-W07L12.qxf
- [ ] Briteq-BT-W12L10.qxf
- [ ] Contest-Tri4U.qxf
- [ ] DTS-Max-FAR.qxf
- [ ] DTS-Nick-NRG1201.qxf
- [ ] Elation-EVC-MH.qxf
- [ ] Elation-Vision-250.qxf
- [ ] Equinox-Gigabar.qxf
- [ ] Eurolite-LED-PMB-8-COB-RGB-30W.qxf
- [ ] Futurelight-MH-660.qxf
- [ ] Futurelight-PHW-260.qxf
- [ ] Futurelight-PHW-700.qxf
- [ ] Generic-Generic-RGB.qxf
- [ ] iSolution-5-Series.qxf
- [ ] iSolution-iMove-250w.qxf
- [ ] JB-Lighting-A12-Tunable-White.qxf
- [ ] JB-Lighting-Varyscan-P6.qxf
- [ ] Laserworld-ES-600B.qxf
- [ ] Martin-MAC-700-Profile.qxf
- [ ] Martin-Viper-AirFX.qxf
- [ ] Philips-Selecon-PLProfile1-MkII.qxf
- [ ] PixelRANGE-PixelPar-44.qxf
- [ ] Robe-ColorSpot-250-XT.qxf
- [ ] Robe-ColorSpot-700E-AT.qxf
- [ ] Robe-ColorWash-1200E-AT.qxf
- [ ] Robe-Pointe.qxf
- [ ] Robe-Robin-100-LEDBeam.qxf
- [ ] Showlite-Flood-Light-Panel-144x10mm-LED-RGBW.qxf
- [ ] Showtec-Acrobat.qxf
- [ ] Showtec-Indigo-4600.qxf
- [ ] Showtec-LED-Light-Bar-RGB-V3.qxf
- [ ] Stairville-Beam-Moving-Head-B5R.qxf
- [ ] Stairville-Quad-Par-Profile-RGBW-5x8W.qxf
- [ ] Stairville-SC250H.qxf
- [ ] Starway-Servo-Beam-5R.qxf

Note: these do not validate by now, due to missing dimensions. Fixing them is welcome, but not needed in this PR.

- [ ] JB-Lighting-Varyscan-2.qxf
- [ ] Lite-Works-ColorChanger.qxf
- [ ] Sagitter-Miniscan-2001.qxf

**Comment by fxedel** [comment]
Thanks for your answer, I'll update the fixtures soon.

Btw: Do the travis tests check the fixtures against the schema? If not, this could be an enhancement.

**Comment by fxedel** [comment]
@janosvitok I tried using the American DJ Accu UFO fixture in QLC+ and I actually saw no reason why capabilities are required:

- The channel `Pan` has no caps
  - Rightclick shows: `Pan`
- The channel `Pan/Tilt Speed` has a 0-255 cap
  - Rightclick shows: `Pan/Tilt Speed | MAX - MIN 0-255` and this huge menu with all DMX values from 0 to 255

=> Using this generic 0-255 capability doesn't improve the UI in my opinion and omitting it doesn't make QLC+ crash or ignore the fixture, so why not allow the lack of capabilities at all?

If doing so, we can set `minOccurs` to 0. In some cases it might also be useful to define a 0-255 capability (e.g. for defining the direction: `focus: 0-255 - far-near`), but it wouldn't be required.

**Comment by fxedel** [comment]
@janosvitok So what do you think about allowing the lack of capabilities?

**Comment by fxedel** [comment]
@janosvitok @mcallegari Any updates on this? Can we safely omit capabilities? If not, I'll update the fixtures that don't pass this regulation so that this PR can be merged sometime.

**Comment by mcallegari** [comment]
@fxedel is this still applicable after the fixture definition rework ?
Technically, a channel with a preset will have no capabilities defined (cause they're implicit)
A "custom" channel instead, will.

**Comment by fxedel** [comment]
Correct; with presets, it doesn't make sense using capabilities. I don't know whether it's possible to either require or forbid capabilities depending on an attribute in xsd schemas. If it's not possible, this PR can be closed.

**Comment by mcallegari** [comment]
I'm gonna close this. The XML schema is turning out to be a waste of my time.
I'm adding validation to the unified python tool and I already found 70 issues not spotted by the schema.

**Pull request closed without merging**
