### PR TITLE
VC/Clock: Added external inputs for controlling countdown/stopwatch

### PR DESCRIPTION
**Pull request by siegmund42**
As requested [here](http://www.qlcplus.org/forum/viewtopic.php?f=18&t=10923&p=47289) I added external input support for the clock widget in countdown and stopwatch mode.
I was not yet able to test feedback, but will this weekend.
I'm not completely sure about the order in the properties dialog but think as it is now is sufficient.

### CODE REVIEW

**Comment by mcallegari** [comment]
Tested and it's working pretty well. Feedbacks seems to be OK too.
Well done !

I just took the liberty of changing the config page layout a bit cause when external input was enabled, the page got too crowdy. A tab solution is cleaner (e.g. see audio triggers widget)

**Comment by siegmund42** [comment]
Tabs are much better, but I think it is a bit confusing that the Input tab is empty when selecting clock. Maybe the input widgets can be grayed out in this case?

**Comment by mcallegari** [comment]
I agree, and I already tried to hide the input tab when selecting the clock mode.
Unfortunately Qt doesn't provide a way to just hide a tab. You need to destroy it and recreate it later.
I think the easier solution for now is to just display a text saying "No input controls available in clock mode"

**Comment by mcallegari** [comment]
Done a135b63a3c50924aeb2bbce9c390a2fab4460ebc

**Pull request merged**
