### PR TITLE
Remove spaces before punctuation

### PR DESCRIPTION
**Pull request by FloEdelmann**
This is basically #1102 again, but this time also for exclamation marks and the commits are split better to help ease reviewing.

* :us: :gb: English: No space before question mark (?) or exclamation mark (!) [<sup>Source</sup>](https://english.stackexchange.com/q/4645)
* :czech_republic: Czech: No space [<sup>Source: janosvitok</sup>](https://github.com/mcallegari/qlcplus/pull/1102#issuecomment-407924137)
* :de: German: No space <sup>Source: How I learned it in school ;)</sup>
* :it: Italian: No space [<sup>Source: mcallegari</sup>](https://github.com/mcallegari/qlcplus/pull/1102#issuecomment-407909930)
* :netherlands: Dutch: No space [<sup>Source: Netflix subtitle translator guidelines, section 14</sup>](https://partnerhelp.netflixstudios.com/hc/en-us/articles/215350158-Dutch-Timed-Text-Style-Guide)
* :es: Spanish: No space, but upside-down question/exclamation mark in front of the (sub)sentence [<sup>Source</sup>](https://www.thoughtco.com/upside-down-punctuation-in-spanish-3080317)
* :fr: French: Spaces mandatory; in software, use non-breaking spaces [<sup>Source: Duolingo</sup>](https://www.duolingo.com/comment/7344/Spaces-before-punctuation-marks)

I've included the updated code comments again; maybe someone else can review them quickly (shouldn't be too difficult in this case). If you prefer, we can revert the respective commits again.

### CODE REVIEW

**Comment by mcallegari** [comment]
132 files this time ! Come on Florian !
This is basically 5 separate topics:

- translations
- code trailing spaces (nice one!)
- documentation
- code comments <-- Again, since I'm the one mostly working on sources, I'd prefer to leave the space even though is syntacticallly incorrect. It's just my choice.
- debug messages (no strong opinion here)

Please split into separate PRs. Thanks         ! :laughing:

**Comment by FloEdelmann** [comment]
Okay, so let's split it up further :D

I'll open the translation PRs once the base PR (#1105) is merged to avoid conflicts.

**Comment by FloEdelmann** [comment]
@mcallegari How should I group / split the PR to remove trailing whitespace?

I've run `find . -name "*.cpp" -type f -print0 | xargs -0 sed -i 's/[[:space:]]*$//'` with a few different file extensions and now there are 267 changed files. That could be a bit much again for one PR and could also cause many merge conflicts in existing PRs.

But at least the "changes" are very easy to review.

**Comment by mcallegari** [comment]
@FloEdelmann I'd say you can split by main folders:

- engine/src
- engine/test
- fixtureeditor
- plugins
- qmlui
- ui

Are there so many trailing spaces around ?? I use QtCreator to edit sources and it is supposed to remove them when I save a file ! I need to double check my settings then

**Comment by FloEdelmann** [comment]
There are a lot of PRs now :sweat_smile: 

* #1108: resources/docs 
* #1109: engine + engine/test
* #1110: plugins
* #1111: qmlui
* #1112: ui
* #1113: webaccess
* #1114: the rest (including fixtureeditor)

**Pull request closed without merging**
