### PR TITLE
vc: add a context menu to widgets (copy/paste/delete)

### PR DESCRIPTION
**Pull request by sammuell**
Adding a basic context menu to the vc. www.qlcplus.org/forum/viewtopic.php?f=35&t=14071

### CODE REVIEW

**Comment by mcallegari** [comment]
The idea is not to use right click menus. So I don't support this change.
v5 is designed to work on mobiles (e.g touchscreens) where you can't possibly right click something!

**Comment by mcallegari** [comment]
I'm not sure what's your plan here, but maybe you should ask before spending your time on these changes.

**Comment by mcallegari** [comment]
And you don't touch the engine.

**Comment by Lichtschalter-5000** [comment]
> The idea is not to use right click menus. So I don't support this change.
> v5 is designed to work on mobiles (e.g touchscreens) where you can't possibly right click something!

Why though? I get your point - you want to preserve usability on all possible devices.
But thereby you're chiseling the possibility to work fast and convenient out of all the users (and I guess this ist the biggest part) with the ability to perform a RMB! See[ this forum thread](https://www.qlcplus.org/forum/viewtopic.php?t=12968)...
Would you state your opinion to that topic, please?

**Comment by mcallegari** [comment]
> Would you state your opinion to that topic, please?

No, I won't, cause you guys are speculating on something unfinished, and I don't have time to waste on pointless discussions.
Has anyone ever asked me what are my plans? No.
If someone did (about context menus) I would have replied: key combinations on desktop, buttons on touchscreens. Where key management is something I completely haven't started to handle yet.
Is it really difficult to ask instead of drawing pointless conclusions?

**Comment by Lichtschalter-5000** [comment]
Sorry, in my opinion you discarded any other suggestions right away with the argument, they couldn't be used with all interfaces. 
So is your statement that alternative methods are still WIP?
My apologies to proceed with the discussion, but in my humble opinion, I did neither draw pointless conclusion nor did I not ask.
- I posted the thread in the issue-reports-thread. In my eyes this equals a question, at least it's a suggestion that something is wrong. A simple "WIP" would have resolved the conflict.
- I did not conclude anything. Based of what you said yourself, I pointed out what I thus thought you would be doing. It seems like I didn't understand what you wanted to make clear or you failed to make it clear in the first place, probably something of both.

**Pull request closed without merging**
