### PR TITLE
debian packaging improvements

### PR DESCRIPTION
**Pull request by trebmuh**
Hope that helps.

### CODE REVIEW

**Comment by mcallegari** [comment]
I'm not sure if the libola-dev dependency is a good idea.
We've got automated linux builds on OBS (OpenSuse Build System) and OLA is problematic.
I already dedicated some efforts to include the OLA plugin in the OBS builds, but in the end I wasn't able to succeed.
When that happens, we can add libola-dev to the dependencies

**Comment by trebmuh** [comment]
Hi @mcallegari and thanks for your answer
Just so you know, the package I've been building for my LibraZiK project (ie: 4.10.5 as of yesterday) is built with this build dependency and everything looks fine from a packaging point of view (ie: it did deb-compiled and I didn't see anything strange in the build description).
LibraZiK is basically a debian "jessie" stable.

I can, remove the build libola-dev dependency if you want and then, you can merge the rest of this commit if it's all good for you. Just let me know.

**Comment by mcallegari** [comment]
> LibraZiK is basically a debian "jessie" stable.

There you have your answer. In a jessie distro, OLA is officially present and supported. On OBS it is not.

> I can, remove the build libola-dev dependency if you want and then, you can merge the rest of this commit if it's all good for you. Just let me know.

Yes, please remove the ola dependency for now, and I'll merge the rest. Thanks.

During the xmas holidays I'll put some more effort to build the OLA plugin on OBS as well.
In case you're interested, this is where it happens: https://build.opensuse.org/project/show/home:mcallegari79

**Comment by trebmuh** [comment]
> Yes, please remove the ola dependency for now, and I'll merge the rest. Thanks.

Done.

> During the xmas holidays I'll put some more effort to build the OLA plugin on OBS as well.
> In case you're interested, this is where it happens: https://build.opensuse.org/project/show/home:mcallegari79

I don't know about OBS. I'll have a look when I free up some time.

**Comment by trebmuh** [comment]
:+1:

**Pull request merged**
