### PR TITLE
Simulate a blinder on an RGB panel.

### PR DESCRIPTION
**Pull request by hjtappe**
This RGB script simulates one or multiple blinders on an RGB panel. It displays the lamp and reflector before finally lighting the while panel as a blinder light effect would do.
I hope this may this be useful when syncing blinder elements on the stage.

### CODE REVIEW

**Comment by sandinak** [comment]
I like this one .. especially when you use a divisor and start+finish colors.  LGTM +1

**Comment by mcallegari** [comment]
Sorry but I don't get what this one is supposed to show.
I tested on a large matrix and it looks like a circle (with bad contour) fading to something I don't understand
Please explain

**Comment by hjtappe** [comment]
Hello Massimo,
I was inspired by this concert which used the LED panels (more LED screens than a simple matrix) to boost their use of blinder lights and used the displays to also simulate blinders.
https://user-images.githubusercontent.com/11509366/104511704-667cd800-55ed-11eb-9187-9d4b277980db.mp4

This is a configuration which works for my small matrices:
Blinder-Chaser
with these elements:
Blinder-On-RGBMatrix
Blinder-Hold-On-RGBMatrix
Blinder-Hold-Off-RGBMatrix

And this is how it finally looks like.

https://user-images.githubusercontent.com/11509366/104511728-75fc2100-55ed-11eb-9f0a-4267a70b9555.mp4

**Comment by mcallegari** [comment]
Alright, this is clear for a small matrix.
Here's a screenshot of what I see on a large matrix
Most likely there is a rounding issue somewhere in the code
Screenshot_20210131_101610

**Comment by hjtappe** [comment]
Thanks for this finding. I updated the part responsible to fil the background color to remove the dark edge.

**Comment by mcallegari** [comment]
Great, thanks!

**Pull request merged**
