### PR TITLE
Remove spaces before question marks

### PR DESCRIPTION
**Pull request by FloEdelmann**
Putting a space before question marks is a mistake in English ([source](https://english.stackexchange.com/q/4645)), as it is in German.

In French, however, they are required, so I replaced them with a non-breaking space (`&#xa0;`) like @nils-van-zuijlen did in the French QLC+ 5 translation.

In Spanish, I assumed that it's always *¿Lorem ipsum dolor?* (without spaces), but I'm not sure.

I don't know about all other translations. If someone else knows though, here is the list of files still containing ` ?`:

* `fixtureeditor/fixtureeditor_ca_ES.ts`
* `fixtureeditor/fixtureeditor_cz_CZ.ts`
* `fixtureeditor/fixtureeditor_it_IT.ts`
* `fixtureeditor/fixtureeditor_nl_NL.ts`
* `fixtureeditor/fixtureeditor_pt_BR.ts`
* `plugins/udmx/src/uDMX_cz_CZ.ts`
* `qmlui/qlcplus_it_IT.ts`
* `ui/src/qlcplus_ca_ES.ts`
* `ui/src/qlcplus_cz_CZ.ts`
* `ui/src/qlcplus_it_IT.ts`

### CODE REVIEW

**Comment by mcallegari** [comment]
No space in italian too

**Comment by janosvitok** [comment]
Czech is the same. No space before: ? ! , . ; : (and maybe others)

**Comment by janosvitok** [comment]
67c4007: you may want to split commit  to make it more readable. Put all non .ts files in one and the .ts files in another. I assume that .ts files changes are from running lupdate and thus don't need to be reviewed.
You forgot to commit qml/showmanager/ShowManager.qml.

226ddd4: I'd do that myself as well :) During my studies I did DTP as part-time job and typos still bother me.

24ce0f1: Seems OK. Trailing space is usually caught by a pre-commit hook or CI...

49bd785: Seems OK, provided that I know almost nothing about French and Spanish.

**Comment by FloEdelmann** [comment]
Moved over to #1104, because I had to `git rebase -i` a lot of stuff and that is cleaner in a new PR.

**Pull request closed without merging**
