### PR TITLE
Add fixture Martin MAC Encore Performance

### PR DESCRIPTION
**Pull request by FloEdelmann**
See #1169.

I've fixed the large gobo file size by simplifying the path in Inkscape, which doesn't decrease the visual quality too much.

### CODE REVIEW

**Comment by mcallegari** [comment]
hmmm doesn't pass schema validation

**Comment by FloEdelmann** [comment]
I know, I'm already working on a fix.

Global `<Physical>` is always required, even if all modes have a `<Physical>` tag themselves. Since the schema can't enforce that either a global physical or all mode physicals are set, I have to write that in the `fixture-tool` validation.

**Comment by mcallegari** [comment]
Why only physical per mode (2 identical if I see it right) and no global at all? In the end I took the global physical idea from OFL ! :sweat_smile: 
This definition should have 1 single global or 1 global + 1 in mode. Not 2 in modes.
Am I missing something?

**Comment by FloEdelmann** [comment]
In this fixture we technically misuse the modes: *CLD* and *WRM* are two different variants of the fixture, but they only differ in the used bulb and color temperature correction filter (channel 7), so merging them into one fixture seems okay. However, setting one bulb in the global physical definition and overwriting it in only one mode seems wrong to me.

We could of course instead change the QLC+ export plugin so that it would use the first mode's physical for the whole fixture and remove the first mode's local one (in cases like this).

**Comment by mcallegari** [comment]
Thanks, sorry for the delay

**Pull request merged**
