### PR TITLE
update audio preview when a different file is loaded

### PR DESCRIPTION
**Pull request by edogawa23**
See this forum [thread]:(https://www.qlcplus.org/forum/viewtopic.php?f=22&t=15924)

This fixes the waveform display at new file load, for me.

### CODE REVIEW

**Comment by mcallegari** [comment]
Hi, thanks for this.
Does it make more sense to move this block of code right after the new width calculation?
Or between width calculation and new duration set? (I don't remember who exactly triggers a repaint)

**Comment by edogawa23** [comment]
We are starting a thread to calculate the new image, isn't it reasonable to do that early so it can finish sooner/process in parallel with the other block?

**Comment by edogawa23** [comment]
I had a closer look, and see no explicit manual (re)painting except via update() during PreviewThread::run()

**Comment by mcallegari** [comment]
prepareGeometryChange requests a repaint (so in our case a width change)
https://codebrowser.dev/qt5/qtbase/src/widgets/graphicsview/qgraphicsitem.cpp.html#7698

Anyway, I'll merge this and do some more tests myself. Thanks :+1:

**Pull request merged**
