### PR TITLE
Add PMJ controller midi input profiles

### PR DESCRIPTION
**Pull request by yestalgia**
Link to Manufacturer: https://pmjcontroller.es/

Controllers:

1. Cabaret [https://pmjcontroller.es/producto/cabaret-controlador-midi/](https://pmjcontroller.es/producto/cabaret-controlador-midi/)
2. Circus [https://pmjcontroller.es/producto/circus-wing-midi-para-ma3/](https://pmjcontroller.es/producto/circus-wing-midi-para-ma3/)
3. MIDIKEY [https://pmjcontroller.es/producto/midikey/](https://pmjcontroller.es/producto/midikey/)

Commit Summary:

[Add: PMJ Cabaret MIDI Input Profile](https://github.com/mcallegari/qlcplus/commit/5edaa2caeb4133ca942e1713714304a8fdb0e7b5)
[Add: PMJ Circus MIDI Input Profile](https://github.com/mcallegari/qlcplus/commit/d44253ab57771c39ad9307b02163495cd057e239)
[Add: PMJ MIDIKEY MIDI Input Profile](https://github.com/mcallegari/qlcplus/commit/fa93d16eb94693d8767de71d915ba39603cb62d5)

### CODE REVIEW

**Comment by mcallegari** [comment]
@yestalgia will we ever get the fixed versions of these?

**Comment by yestalgia** [comment]
> @yestalgia will we ever get the fixed versions of these?

I'll email them again - shouldn't take long to fix

**Comment by yestalgia** [comment]
This is now ready to merge.

**Comment by mcallegari** [comment]
Please remove (again) 9 faders controller. It's already upstream
Please rename "MIDIKEY" to "MidiKey" as indicated in the their website

**Comment by mcallegari** [comment]
Please rename also the file to PMJ-MidiKey.qxi, thanks

**Pull request merged**
