### PR TITLE
VCCuelist: Set Crossfader top labels to fixed width, honouring current font metrics

### PR DESCRIPTION
**Pull request by edogawa23**
3rd attempt :)

### CODE REVIEW

**Comment by kripton** [comment]
Just as a side note: You don't need to create a new PR if you want to add some commits. If you push new commits to a branch which still has a PR open, they will be automatically added to the PR :)

**Comment by mcallegari** [comment]
I was about to say what @kripton said.
Alright, let's merge this. Thanks

**Comment by edogawa23** [comment]
Thank you for letting me know about how PRs deal with further commits. In this case I both times had continued to work on other ideas I had, in the same local master branch (I see now how creating branches for dedicated tasks is useful ;)). To separate the new work from modifying the patch for this PR seemed over complicated. As I decided to ditch the other ideas anyways for now, so I simply hard-reset my fork to upstream and recreated and modified my patch.
Please excuse me as I'm fairly new to git and github, and in the process of getting familiar with ways of doing things. Also my C skills are DIY and around 20 years old, and as you have seen i don't know much about C++... time to read up and familiarize myself with certain advanced C++ features, I guess :)

Anyway, thanks for merging!

**Comment by mcallegari** [comment]
No worries. GIT is an obscure beast for me too sometimes.
They made it too complicated for newbies.

**Pull request merged**
