### PR TITLE
Function startstop 09

### PR DESCRIPTION
**Pull request by plugz**
This fixes the issue "scene in a very quick chaser may stay ON after the end of the chaser"

### CODE REVIEW

**Comment by mcallegari** [comment]
@plugz  I like this one ! :+1: 
Let's see what Travis old fart says :construction_worker: 

Sooner or later we should add a test unit for Sequences, Right now they are not covered and every change to Scene/Chaser/Function/MasterTimer can affect them.
I will think of something that makes sense, unless you're faster than me :smiley:

**Comment by plugz** [comment]
:)

**Comment by mcallegari** [comment]
Should we merge this then ?

**Comment by plugz** [comment]
Yes

**Pull request merged**
