### PR TITLE
Alternatespeed

### LINKED ISSUE #758: RGB matrix fadein is broken when starting an RGB matrix from a VC slider
Because of this:
https://github.com/mcallegari/qlcplus/pull/699
(sorry)

This can be fixed by simply ignoring overridefadein and overridefadeout.
Or use them differently (use them as global fade in and fade out speed instead of step fadein and fadeout speed).
Or revert 699.

The issue is the same for chasers, and a fix could fix this issue too: https://github.com/mcallegari/qlcplus/issues/445

### PR DESCRIPTION
**Pull request by plugz**
This could be split in 2 pull requests:

- fix #758, #445, #193.
- introduces chaser step speed change through VCSpeedDial.

Details in the commit messages.

### CODE REVIEW

**Comment by plugz** [comment]
Screenshots of the speed dial properties & the function selection tool:

2 AlternateSpeed from a chaser are affected by this speed dial:
speed dial properties_002

When trying to add other functions or function alternate speeds in the speed dial, the currently selected alternate speeds are grayed (as is currently the case with functions)
select function_003

**Comment by mcallegari** [comment]
Ouch ! Perfect timing to conflict with what I am doing in the bpm branch :sob: 

By the way, how does the Function selection widget behave with Sequences ?

**Comment by plugz** [comment]
> Ouch ! Perfect timing to conflict with what I am doing in the bpm branch :sob: 

Yes, I've seen you've been working on this too. Sorry about that :smile: 

For sequences, it simply writes "step 0", "step 1"... instead of "0.function0", "1.function1"....
Other than this, the behavior is the same.

I'll post a screenshot of a sequence in the function selection tool tonight if you want.

**Comment by plugz** [comment]
Here are screenshot with a sequence

speed dial properties_004

select function_005

**Comment by janosvitok** [comment]
If you need help merging alternatespeed and bpm, let me know.

Nitpicking: steps in UI should be numbered from 1, not 0, it's more "human" :)

**Comment by plugz** [comment]
Too many conflicts with the bpm stuff :(

**Comment by mcallegari** [comment]
What about my proposal of "speed override priority" ?

**Pull request closed without merging**
