### PR TITLE
EFX gradient size should be 256x256

### PR DESCRIPTION
**Pull request by grebecchi**
Gradient size should be 255x255 because it is accessed by EFX when RGB mode is used.
After my initial commit, gradient x size was changed to 252 to reflect the ClickAndGoWidget size.

Now I have correct the Gradient and the  ClickAndGoWidget x size to 255.

### CODE REVIEW

**Comment by mcallegari** [comment]
This is wrong anyway.
Also, I renamed the title of this PR.

The calculation for 6 base colors is:
256 / 6 = 42.6666
Approximated to 42
42 * 6 = 252

Your change doesn't include a fix for the approximation, so resizing the pixmap to 256 pixels will produce a strip of 4 black (or random) pixels on the right.

A proper fix is to add a method to rescale the generated gradient pixmap to the desired size and use it in the EFX class. Something like this:

void  Gradient::resizePixmap(int width, int height)
{
    m_rgb = m_rgb.scaled(width, height);
}

I haven't tested it though

**Comment by grebecchi** [comment]
Hi Massimo, I have reverted ClickAndGoWidget and Gradient size.
I have fixed this problem (EFX use x coordinates until 255 while Gradient has an image of 0-251 pixels) making a check on Gradient::getRGBColor. Input x and y parameters of Gradient::getRGBColor are now checked that contain a valid value.

**Comment by mcallegari** [comment]
I'm afraid this is still not right.
Basically a Gradient is a lookup table when used by the EFX class. If the QImage is 252 pixels wide, you will still have 4 pixels handled not properly.
If you test your change with a Square EFX in RGB mode, you will notice that the last 4 horizontal pixels will return the same color. Not a big deal, but I guess this is not what we want.

I think the only way is to rescale the QImage to the needed size, as I suggested.
You just need to find a proper place in the EFX class to call the rescale method.

**Comment by grebecchi** [comment]
Yes I know, this is a work around. 
X pixels are truncated to 252, the difference between 252 and 255 is a little difference, imperceptible in real RGB animations.

In the next commit I can change and store a static rescaled QImage in EFXFixture (so in it shared for all EFXFixture).

**Comment by mcallegari** [comment]
Merged, thanks :+1:

**Pull request merged**
