### PR TITLE
Fix concurrent MIDI issue on Mac

### PR DESCRIPTION
**Pull request by Timebutt**
This issues fixes issue #1390.

### CODE REVIEW

**Comment by mcallegari** [comment]
I see this patch is for macOS.
Have you checked the issue doesn't happen on Windows and Linux?

**Comment by Timebutt** [comment]
I have not been able to reproduce this on Windows or Linux yet, however: when I look at the implementation of `win32midiinputdevice.cpp`, I don't see code that could lead to the same issue. I will try and set up the same situation (a virtual MIDI device is harder to set up on Windows than Mac). 

I have meanwhile renamed the PR so that it more accurately reflects the issue.

**Comment by kpr0th** [comment]
For what it's worth, I just tried testing with LoopBe on Win11.  I used MultiPlay 3.x to send 2 MIDI messages in one click, and both of them came through successfully (I added some temporary qDebug lines to prove they both came into win32midiinputdevice.cpp::MidiInProc(), and they came through as two separate calls to this function. As such, I suspect the loop fix proposed for macx doesn't apply in the windows world.

**Comment by Timebutt** [comment]
Awesome, thanks for checking @kpr0th!

**Pull request merged**
