### PR TITLE
French translations for QLC+ 5

### PR DESCRIPTION
**Pull request by nils-van-zuijlen**
See #1076.

Everyone who has write access to the QLC+ repository can contribute on this PR to add French translations.

This PR is just to avoid duplicate work when several people create the same translations locally.

*Si vous voulez m'aider, commencez par la fin, ou avant la dernière traduction réalisée pour qu'on ne se marche pas sur les pieds.*

### CODE REVIEW

**Comment by mcallegari** [comment]
@nils-van-zuijlen please let me know when this can be merged

**Comment by mcallegari** [comment]
@nils-van-zuijlen thanks a lot for this. Just a minor that I found: in ShowItem, "Position: " has semicolon and space afterward. You translated the opposite "Position :". I can fix it anyway.

**Comment by nils-van-zuijlen** [comment]
@mcallegari I fixed that. Thank you for pointing it out.

**Comment by mcallegari** [comment]
Thanks :+1:

**Comment by jeromelebleu** [comment]
@nils-van-zuijlen Nice job!! I've started a review - that I'll try to finish as soon as possible - even if it's already merged. I thought it was easier to do like that in order to be able to discuss, I hope you'll find that too!

**Pull request merged**
