### PR TITLE
deal with new flush API for buffers in recent libftdi1 1.5

### PR DESCRIPTION
**Pull request by edogawa23**
https://www.qlcplus.org/forum/viewtopic.php?f=12&t=14804

Updated the patch to act conditionally, depending on which libftdi version is found at compile time.

### CODE REVIEW

**Comment by mcallegari** [comment]
If this is for libftdi 1.5 only then using LIBFTDI1 is wrong. It involves all 1.x versions

**Comment by edogawa23** [comment]
You're right, I've added a version check and new variable to src.pro

**Comment by mcallegari** [comment]
It looks too complicated to me. Moreover, does it work on macOS?
I would simply use the `ftdi_get_library_version` in the original `LibFTDIInterface::purgeBuffers` method and decide to invoke `ftdi_tcioflush` or `ftdi_usb_purge_buffers`.
That's all. Simple and clean.

**Comment by edogawa23** [comment]
Yeah I just tried and ran into problems, I can't use the deprecated function name from C++.

Not sure how to check macOS behaviour, the only Macbook I have access to is the machine used for editing and running shows at the theater, and not set up for compiling stuff - I rather wouldn't mess with it at this time.

**Comment by mcallegari** [comment]
I think you dragged in unrelated MIDI code in this PR. Please rebase/fix.

Also, please instead of purge/flush as separate methods, make a single change in LibFTDIInterface::purgeBuffers and ifdef the FTDI versions. This way it looks cleaner than multiple ifdefs around.
Thanks

**Comment by edogawa23** [comment]
Sorry for the MIDI stuff, i had merged your master branch - still unsure about best practices in GH...

I thought the method name should reflect what it's doing, but if you prefer this simpler way, I'm totally fine with that :)

Hopefully it's ready now for merging?

**Comment by mcallegari** [comment]
Yeah, thanks. I need to check if this is OK on macOS and then it can be merged

**Comment by mcallegari** [comment]
@edogawa23 I finally checked on macOS and this seems OK 👍 
One last change: can you please rename "NEW_LIBFTDI1" to "LIBFTDI1_5"? I doubt "NEW" will still make sense in 5-10 years ;)
Also, can you simplify the version check like the following? 
Does it really make sense to check all the non-verified conditions and do nothing first?
```
versionAtLeast(ftdi1, 1.5) {
    message("Found libftdi1 version $$ftdi1 (new buffer flush API)")
    DEFINES += LIBFTDI1_5
}
```

**Comment by mcallegari** [comment]
Thanks! :+1:

**Pull request merged**
