### PR TITLE
Android build v5

### PR DESCRIPTION
**Pull request by Binary-Vanguard-12138**
Used Android SDK31/33, JDK17, NDK21/25, and gradle 7.3 on Windows/Ubuntu Qt.
It crashes in Nox emulator, will need to test it on real device and check if it works.

### CODE REVIEW

**Comment by Binary-Vanguard-12138** [comment]
Adb log attached.
`
02-09 02:32:33.026  2102  2102 W PropertyValuesHolder: Method setDesaturation() with type float not found on target class class d.b.a.k.x
02-09 02:32:33.026  2102  2102 W PropertyValuesHolder: Method getDesaturation() with type null not found on target class class d.b.a.k.x
02-09 02:32:33.026  2102  2102 W PropertyValuesHolder: Method setBrightness() with type float not found on target class class d.b.a.k.x
02-09 02:32:33.026  2102  2102 W PropertyValuesHolder: Method getBrightness() with type null not found on target class class d.b.a.k.x
02-09 02:32:33.028  1651  1709 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 4, track 44100 Hz, output 48000 Hz
02-09 02:32:33.028  1651  1661 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.qlcplus/org.qtproject.qt5.android.bindings.QtActivity bnds=[1264,207][1496,366] (has extras)} from uid 1000 on display 0
02-09 02:32:33.062  2102  2534 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1435 android.content.ContextWrapper.bindService:636 cm.d:12 bw.d:5 bn.c:13
02-09 02:32:33.071  1651  1887 I ActivityManager: Start proc 3152:org.qlcplus/u0a49 for activity org.qlcplus/org.qtproject.qt5.android.bindings.QtActivity
02-09 02:32:33.071  3152  3152 I art     : Late-enabling -Xcheck:jni
02-09 02:32:33.071  3152  3152 W art     : Unexpected CPU variant for X86 using defaults: x86_64
02-09 02:32:33.088  2506  2506 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
02-09 02:32:33.088  2506  2506 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
02-09 02:32:33.102  1521  1568 D gralloc_nox: gralloc_alloc: Creating ashmem region of size 5763072
02-09 02:32:33.117  3152  3152 W System  : ClassLoader referenced unknown path:
02-09 02:32:33.130  3152  3152 D Qt JAVA : Class org.qtproject.qt5.android.multimedia.QtMultimediaUtils does not implement setActivity method
02-09 02:32:33.167  3152  3170 I QtCore  : Start
02-09 02:32:33.355  3152  3170 I Qt      : qt started
02-09 02:32:33.413  3152  3152 D         : static std::unique_ptr<HostConnection> HostConnection::createUnique(uint32_t): call
02-09 02:32:33.414  3152  3152 D         : HostComposition ext GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_depth24 GL_OES_depth32 GL_OES_element_index_uint GL_OES_texture_float GL_OES_texture_float_linear GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_EXT_texture_format_BGRA8888 GL_APPLE_texture_format_BGRA8888 GL_OES_texture_half_float GL_EXT_robustness GL_OES_texture_half_float_linear GL_OES_packed_depth_stencil GL_OES_vertex_half_float GL_OES_texture_npot GL_OES_rgb8_rgba8 GL_EXT_color_buffer_float GL_EXT_texture_sRGB_decode ANDROID_gles_max_version_3_1 GL_OES_vertex_array_object GL_EXT_texture_buffer GL_EXT_copy_image GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_EGL_image_external
02-09 02:32:33.441  1521  1566 D gralloc_nox: gralloc_alloc: Creating ashmem region of size 4096
02-09 02:32:33.441  3152  3175 D         : static std::unique_ptr<HostConnection> HostConnection::createUnique(uint32_t): call
`

**Comment by Binary-Vanguard-12138** [comment]
@mcallegari 
It works after I change the settings in Nox, so it is not the problem of the project.

image

**Comment by mcallegari** [comment]
Thanks :+1: 
Will post back here if I found anything

**Comment by mcallegari** [comment]
@Itay-Lifshitz I've been able to run QLC+ on Android but the generated apk is missing all the resource files (fixtures, gobos, profiles, ect)
It seems nothing is installed in the assets folder. Can you please have a look? thanks

**Comment by Binary-Vanguard-12138** [comment]
> @Itay-Lifshitz I've been able to run QLC+ on Android but the generated apk is missing all the resource files (fixtures, gobos, profiles, ect) It seems nothing is installed in the assets folder. Can you please have a look? thanks

OK, will take a look.

**Comment by Binary-Vanguard-12138** [comment]
@mcallegari How does the `assets` directory look like?
Does it contain the subdirectories of `resources` folder such as fixtures, gobos, etc in it?
Or does it first contain `resources` folder in `assets` and subfolders in `resources`?

**Pull request merged**
