### PR TITLE
Add test button to Collection

### PR DESCRIPTION
**Pull request by grebecchi**
In this pull request I have implemented the test button for collections.
This is very usefull to test collections directly from editor.

### CODE REVIEW

**Comment by janosvitok** [comment]
Nice!

**Comment by mcallegari** [comment]
Hey thanks.
Apart for a minor copy/paste error, this looks OK to me.

I'm not sure about the treewidget sorting (it was there before your change)
In a Collection, the stacking order is very important, so the tree should not be sorted.

Anyway, if you fix the string, then I'll merge this

**Comment by grebecchi** [comment]
I agree about treewidget sorting. 
In my last commit I have fixed tooltip string and disabled sorting.

**Comment by mcallegari** [comment]
Great, thank you very much :+1:

**Pull request merged**
