### PR TITLE
Refresh Cue List Widget on Addition or Removal of a Step from Chaser

### PR DESCRIPTION
**Pull request by lilyCalla**
- Currently adding or removing a widget is not reflected in the cue list widget unless the project is saved and reopened 
- Also apparent cause of crash at https://www.qlcplus.org/forum/viewtopic.php?t=17147, as the cue list would attempt to access a non-existent index
- This PR reloads the chaser cue list if a function is added or removed from the linked chaser, allowing updates to be seen in real time and preventing the crash

### CODE REVIEW

**Comment by yestalgia** [comment]
Love your work @lilyCalla

**Comment by mcallegari** [comment]
Looks good, thanks 👍

**Comment by mcallegari** [comment]
Actually, I overlooked these changes.
- first signals should be using past form, so in chaser.h/cpp it's `stepsListChanged`, not `stepListChange`
- also, a signal to update the UI was already present: https://github.com/mcallegari/qlcplus/blob/master/qmlui/virtualconsole/vccuelist.h#L198

I think the only change needed in vccuelist.cpp is this:
connect(function, SIGNAL(stepsListChanged(quint32)),
                this, SIGNAL(stepsListChanged()));

Please try that and re-submit a new PR. Thanks

**Comment by mcallegari** [comment]
Nevermind, I sorted this myself.

**Pull request merged**
