### PR TITLE
Function Start/Stop source

### PR DESCRIPTION
**Pull request by plugz**
This is a huge engine change.

Basically put: A function keeps a list of 'what' started it. 'What' is called a 'function source' (but the name may be changed)

As long as at least one 'function source' is present in a function's list, the function will not be stopped.

As-is, this PR break qmlui build. I'll fix it before merging the PR, I just want to discuss the PR before.

### CODE REVIEW

**Comment by plugz** [comment]
This fixes #705

**Comment by mcallegari** [comment]
Uhm...why does this conflict ? Did I cause it ?

Can we rename "Source" into "FunctionSource" or "ParentSource" or "Parent" ?

Can you add some comments that explain the meaning of the SourceType enums ? (for example, what's the difference between AutoVCWidget and ManualVCWidget ?)
And who is this God after all ? :laughing: 
Can we call it "Master" or "MasterOfTheUniverse" or simply "He-Man" ? :laughing: 

What's the difference between God and Mask ?
Or is it a single entity called [Mixcoatl](https://en.wikipedia.org/wiki/Mixcoatl), the masked god ? :)

**Comment by plugz** [comment]
> Uhm...why does this conflict ? Did I cause it ?

I probably caused this, don't worry

> Can we rename "Source" into "FunctionSource" or "ParentSource" or "Parent" ?

Yes, it could even go into it's own .h and .cpp files.

> Can you add some comments that explain the meaning of the SourceType enums ? (for example, what's the difference between AutoVCWidget and ManualVCWidget ?)

Will do


> And who is this God after all ? :laughing:

I don't know I never met him :(
But he has the power to stop running functions !

**Comment by plugz** [comment]
continued as #787

**Pull request closed without merging**
