### PR TITLE
Completed adding button monitor feedback for midi controllers

### PR DESCRIPTION
**Pull request by ditcheshurt**
I though it would be visually helpful for users of Midi controllers that have back-lit or otherwise feedback enabled button midi controllers to see what functions that have been activated by another function (monitoring) to create the same visual feedback you already have with the virtual console buttons.

I'm using an Akai APCMini for testing these changes and wanted to contribute to this amazing software and project.

### CODE REVIEW

**Comment by yestalgia** [comment]
This would fix #1413

**Comment by yestalgia** [comment]
https://www.qlcplus.org/forum/viewtopic.php?t=12839

Another request for this feature

**Comment by mcallegari** [comment]
I finally merged this and found a few errors:

- the word "Value" was removed from labels (luckily I saw this)
- the monitoring spinbox was visible also for non button widgets

Now it's fixed. Thanks for contributing.

**Comment by yestalgia** [comment]
Huge improvement! Thanks guys :)

**Pull request merged**
