### PR TITLE
Add fixture: Varytec Hero Spot Wash 80 2in1 RGBW+W

### PR DESCRIPTION
**Pull request by hjtappe**
With this, I am adding the moving head with spot and wash function, including the related Gobos, where only slightly similar ones existed but did not fully match. These gobos are in fact also used in other moving heads (such as in the Showtec Shark series), but did not yet exist in the gobos library yet.

The manual can be found here: https://images.static-thomann.de/pics/atg/atgdata/document/manual/451570_c_451570_v2_en_online.pdf

Do we want to provide PNG files next to *all* SVG files to make them better identifiable in Windows (Explorer gallery view)? It could be accomplished with a bash script:
`for i in resources/gobos/*/*.svg; do if [ ! -f $(basename "$i" .svg).png ]; then echo "Missing; $i"; inkscape -z -w 64 -h 64 "$i" -e $(basename "$i" .svg).png; fi; done`

### CODE REVIEW

**Comment by hjtappe** [comment]
Hello @mcallegari, the build failure seems unrelated as the stdlib.h is not found. Can you re-trigger the build or still merge or do I need to push some unrelated change?

**Comment by mcallegari** [comment]
Seems like Appveyor updated gcc (v. 11) and Qt is no longer compatible with it. Nice.
You don't need to do anything. That's another thing to fix on me.

**Comment by mcallegari** [comment]
Hi, sorry, I just created a conflict with this.
I also realized you were trying to push PNG gobos... Please don't. They're not compatible with QLC+ 5.
All of the Hero Spot Wash 80 gobos are already in the library (I just checked) 
Please use the existing ones, thanks

**Comment by mcallegari** [comment]
As for SVG previews:
https://joshuawinn.com/how-to-preview-svg-files-in-windows-10-file-explorer-without-3rd-party-extensions/

**Comment by mcallegari** [comment]
This should be it
```
 <Channel Name="Gobo">
  <Group Byte="0">Gobo</Group>
  <Capability Min="0" Max="10" Preset="GoboMacro" Res1="Others/open.svg">Open</Capability>
  <Capability Min="11" Max="20" Preset="GoboMacro" Res1="Robe/gobo00025.svg">Gobo 1</Capability>
  <Capability Min="21" Max="30" Preset="GoboMacro" Res1="SGM/gobo00008.svg">Gobo 2</Capability>
  <Capability Min="31" Max="40" Preset="GoboMacro" Res1="Others/gobo00108.svg">Gobo 3</Capability>
  <Capability Min="41" Max="50" Preset="GoboMacro" Res1="Others/gobo00112.svg">Gobo 4</Capability>
  <Capability Min="51" Max="60" Preset="GoboMacro" Res1="Chauvet/gobo00034.svg">Gobo 5</Capability>
  <Capability Min="61" Max="70" Preset="GoboMacro" Res1="Others/gobo00125.svg">Gobo 6</Capability>
  <Capability Min="71" Max="80" Preset="GoboMacro" Res1="Others/gobo00126.svg">Gobo 7</Capability>
  <Capability Min="81" Max="90" Preset="GoboShakeMacro" Res1="Robe/gobo00025.svg">Gobo 1 Shake</Capability>
  <Capability Min="91" Max="100" Preset="GoboShakeMacro" Res1="SGM/gobo00008.svg">Gobo 2 Shake</Capability>
  <Capability Min="101" Max="110" Preset="GoboShakeMacro" Res1="Others/gobo00108.svg">Gobo 3 Shake</Capability>
  <Capability Min="111" Max="120" Preset="GoboShakeMacro" Res1="Others/gobo00112.svg">Gobo 4 Shake</Capability>
  <Capability Min="121" Max="130" Preset="GoboShakeMacro" Res1="Chauvet/gobo00034.svg">Gobo 5 Shake</Capability>
  <Capability Min="131" Max="140" Preset="GoboShakeMacro" Res1="Others/gobo00125.svg">Gobo 6 Shake</Capability>
  <Capability Min="141" Max="150" Preset="GoboShakeMacro" Res1="Others/gobo00126.svg">Gobo 7 Shake</Capability>
  <Capability Min="151" Max="255" Preset="RotationClockwiseFastToSlow">Gobo Rotation</Capability>
 </Channel>
```

**Comment by hjtappe** [comment]
Thanks, I will fix these issues in a week.

**Comment by hjtappe** [comment]
Hello @mcallegari
I changed the gobos as per your proposal and removed the extra files.
Please also check the (usefulness of) the added line in resources/fixtures/FixturesMap.xml as I am not completely sure if that should be there or if the entry in the fixture file itself would be sufficient. Should I remove the line or should it stay?

**Comment by hjtappe** [comment]
I was also wondering if the spot and wash would have to be represented in two heads, but it seems, putting them into one head works for me.

**Comment by hjtappe** [comment]
Thanks for removing the leftover channels with your review. I was blind by looking at it too long and forgot to remove them at the end.

**Pull request merged**
