### PR TITLE
Build using GitHub actions

### PR DESCRIPTION
**Pull request by hjtappe**
@mcallegari, this is a first version of a github actions workflow to build the Linux variants.

In the project's actions settings, I configured the project to be restrictive with two exceptions.
grafik

The apt cache does seem to install only the first time it runs, so I added a fallback APT installation step.

It would be possible to add and run also the Windows build later as a second job.

As it was a longish way to get to this configuration, you may consider to squash-merge this pull request.

### CODE REVIEW

**Comment by mcallegari** [comment]
Hi @hjtappe thanks for this
Just one suggestion that I found while studying around the topic. It seems there's a shortcut to install Qt:
https://github.com/marketplace/actions/install-qt
Maybe it's worth a try to simplify the manifest?

**Comment by hjtappe** [comment]
@mcallegari, I can do that. Is there still a need for ppa:ubuntu-toolchain-r/test ? I do not see that any package of that one is requested. It might resolve the problems with the apt cache.

Is there a way to disable Travis for this branch? Otherwise, I am using unnecessary Travis minutes. Or I branch another time locally on my side only.

**Comment by mcallegari** [comment]
Perhaps removing the travis.yml file will not trigger a build? (which in the end is the purpose of this PR ;))

**Comment by mcallegari** [comment]
Hey @hjtappe thanks a lot for this huge work you're doing!
If there's anything I can do to help/assist you, please ask.
I'm wondering why you had to adopt static Qt on windows. Is dynamic not working?

**Comment by hjtappe** [comment]
Hello @mcallegari, I probably was a bit too ambitious when starting the work on the Windows build to offer that one as a replacement for appveyor. Windows is a world full of incompatibilities for host and target architectures and programs in the PATH variable. But I have hope because it should technically be possible.

The QT statis is (currently) needed due to:
`make[3]: *** No rule to make target 'D:/c/opt/Qt/5.15.2/msvc2019_64/lib/libQt5Gui.a', needed by 'libhotplugmonitor.a'.  Stop.`

I briefly wondered about that and then followed the path to remove this one error (just to see other problems due to changed paths). It could be possible to go back to the non-static QT later once I or we understand more of it.

If you run out of Travis minutes again, send me a ping and I can disable Windows, enable Linux and we are good to go. I can continue to debug & setup the Windows build on another branch then. I will send you an update on the actions configuration then because we are now using more actions than in the screenshot at the beginning of this pull request.

If you have ideas on how to setup the msys2 win32/i686 environment (or should we shift to amd64?) for the Windows build or have pleasure to work on it, we can certainly arrange something on a branch until one of us finds a way to make it pass. :-)

**Comment by mcallegari** [comment]
I do use MSYS2 on Windows to build QLC+.
Yeah, sometimes it includes frustrating outcomes, but in general it proved to work over the years.
I see something not right in the path you shared: /c/opt/Qt/5.15.2/msvc2019_64 is unexpected.
It seems you're either using the official Qt version for Windows or a MSVC variant of it.
Right now on MSYS2 the Qt version is 5.15.7 and it's for mingw32/64. That's the one you should use.
Example:
https://ci.appveyor.com/project/mcallegari/qlcplus/builds/45260155#L673

Setup of the environment is in appveyor.yml

**Comment by hjtappe** [comment]
Yes, I still have appveyor.yml open to find the trick. It's the file I started with before running into problems. It seems that the image selected in appveyor.yml is already different. On Github, it started with not finding pacman, and then proceeded with problems finding the right version of msys2 (32bit versus 64bit) etc.:
https://github.com/mcallegari/qlcplus/pull/1369/commits/415389118dc4042818d54a8101a35b2c1203fd63

**Comment by hjtappe** [comment]
@mcallegari, it looks like I am in a dead end with the current approach (qmake refuses to run g++) and I consider to rewind to zero (appveyor.yml standards) to find my luck with what I learned along the way about msys and Windows builds and github actions.

I need to suspend my work on this for at least a few days if not weeks. If you have experience in getting the Windows build to work, you could try to find the right parameters to setup the system consistently - or I can try on another branch. The actions documentation can be found on the github actions marketplace (https://github.com/marketplace?type=actions) and the msys2 documentation on the msys pages (https://packages.msys2.org/package/). Migrating the Windows build does not have a huge priority though, I think.

So I would propose, you could configure the actions permissions in your repository and then merge pull request to replace the travis build and we see how to proceed with the (deactivated) windows build:

`awalsh128/cache-apt-pkgs-action@*,
chocobo1/setup-ccache-action@*,
egor-tensin/setup-mingw@*,
jurplel/install-qt-action/action@*,
jurplel/install-qt-action@*,
msys2/setup-msys2@*,`

**Comment by mcallegari** [comment]
OK, for now I would do this: migrate only the Linux builds to GH and abandon Travis.
Then I can invest some time also on Windows (and macOS) builds.
One question: does GH produce artifacts? Meaning: can I take the result of a build (.deb, .exe, .dmg) and upload it somewhere of my choice?
One advantage of Appveyor right now is that I can upload any build to the QLC+ website FTP very easily.
Losing this possibility would be a step backward for the project.

Another thing is coverage. If I remember correctly, once the "coverage" target is built by Travis, a trigger is invoked to pass the result to Coveralls. It would be interesting to keep this sort of mechanism also with GH and display a badge here:
https://github.com/mcallegari/qlcplus/wiki

It took me months to sort out all these mechanisms so I didn't expect this task to be easy at all (and that is why I haven't started this crusade myself yet 😉)

**Comment by hjtappe** [comment]
Yes, github can handle artefacts but as default is storing them in the build, see https://github.com/marketplace/actions/upload-a-build-artifact and https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

There are actions to upload to FTP though: https://github.com/marketplace?type=actions&query=Upload+FTP which can be used as a final step.

For Windows, an artefact would be built, for QML, the Appimage could be composed through  https://github.com/marketplace/actions/build-appimage.

Not sure that this is possible for version 4/qt, but could be.

The coverage build is passing, the coverage will be uploaded through the related coveralls action.

Not sure why the appveyor build currently fails here. I  do not see how that would be affected. Should I briefly merge master to make it pass on the USB compile error?

**Comment by mcallegari** [comment]
Hi @hjtappe Windows builds started to fail because it was not possible anymore to revert to an older GCC.
This is a problem indeed and will eventually lead to adopt Qt 6.x quite soon.
In the meantime I applied a barbaric patch to build with GCC 12.x. So yes, merging master should be it.
As soon as I have some time, I will go back to the Qt 6 port and finalize it (I think everything works except for audio on some platforms)

**Comment by ETE-Design** [comment]
@mcallegari Looking forward for the Windows Build to work... That way it will always be possible to download Edge Build without having to compile it myself right?

**Comment by mcallegari** [comment]
> @mcallegari Looking forward for the Windows Build to work... That way it will always be possible to download Edge Build without having to compile it myself right?

Test builds can be found here: https://www.qlcplus.org/downloads/test/index.php?p=

**Comment by ETE-Design** [comment]
> > @mcallegari Looking forward for the Windows Build to work... That way it will always be possible to download Edge Build without having to compile it myself right?
> 
> Test builds can already be found here: https://www.qlcplus.org/downloads/test/index.php?p=

Is that Edge Build for QLC+ 5?

**Comment by mcallegari** [comment]
Hi @hjtappe is this PR ready for merge?
Can we switch to GitHub actions?

**Comment by hjtappe** [comment]
> Hi @hjtappe is this PR ready for merge? Can we switch to GitHub actions?

Well:
- The Linux build is running
- The Windows build needs work, it does not run currently
- You asked to create an artifact, so I added that.
- The qt5 (QLC+ v4) AppImage artefact is starting and running.
- The qt5qml (QLC+v5) AppImage artefact fails (on Github, not on my local installation) with:
`./qlcplus-qml: symbol lookup error: ../lib/x86_64-linux-gnu/libqlcplusengine.so.1: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcmRKS3_, version Qt_5`

It seems to be a GCC ABI problem, induced by how the QT libs are built

I consider to separate the build steps completely and to install QT v6 for the qt5qml build.

Alternatively, I could revert installing the QT binaries from a different source (not using the action script currently used.

So, we might switch to the Linux Google Action build and address the Windows and AppImage ABI problem i a separate pull request branch. Let me cleanup the working copy before you actually merge, though.

What is your desired maturity before merge (a. build running and reporting Linux compile & test problems, b. Build providing a runnable Linux artifact, c. Build providing artifacts for Linux and Windows, d. something else)?

**Comment by mcallegari** [comment]
Hi @hjtappe don't worry about errors. I can help to fix them!
The important thing is that the structure is in place.
I'd say let's merge this and then fix it together.

**Comment by hjtappe** [comment]
OK, so here we go. The current status:
- qt5 (v4) builds an AppImage, but I had to add the `-fno-sized-deallocation` option to g++, otherwise, it would not run un Ubuntu 22.04 (the build is using 20.04 and seems to have some ABI change)
- qt5qml (v5) builds an AppImage, but it fails to run due to other ABI incompatibilities, potentially due to how the downloaded QT was built. I added a build-step to test-load the application, but with `--help`, it does not run into the undefined symbol.
- Windows build is deactivated, I failed to bring the pieces together in a compatible configuration. 

Note the Actions configuration at the beginning of this thread. The following actions are currently configured:
`awalsh128/cache-apt-pkgs-action@*,
chocobo1/setup-ccache-action@*,
egor-tensin/setup-mingw@*,
jurplel/install-qt-action/action@*,
jurplel/install-qt-action@*,
msys2/setup-msys2@*,`

Feel free to merge it if you feel comfortable with this status. You might consider to resurrect the travis files until the build artefacts are usable.

**Comment by ETE-Design** [comment]
@mcallegari Can you pls. Compile QLC+ v5 with newest changes... Would really like to try it, but Beta 2 had some defects / missing pieces so my setup dosen't work :-(

**Comment by mcallegari** [comment]
@hjtappe  Questions:
- according to [this](https://github.com/marketplace/actions/install-qt) it should be `jurplel/install-qt-action@v3`
- is `egor-tensin/setup-mingw` needed if there is `msys2/setup-msys2`?
- is http_parser changes needed for GA to work? (or can we separate that in another PR)

**Comment by mcallegari** [comment]
> @mcallegari Can you pls. Compile QLC+ v5 with newest changes... Would really like to try it, but Beta 2 had some defects / missing pieces so my setup dosen't work :-(

Please do not hijack GitHub threads to ask personal questions. Use the forums instead.
And btw, I'll build v5 when I think it's worth to build it

**Comment by hjtappe** [comment]
Hello @mcallegari,

> @hjtappe Questions:
>     * according to [this](https://github.com/marketplace/actions/install-qt) it should be `jurplel/install-qt-action@v3`

https://github.com/mcallegari/qlcplus/blob/8464aff27e659968cbb061d26bf67881f44496d8/.github/workflows/build.yml#L105
In line 105, this is what I think I see. Which line do you refer to - or what is missing, please? In the security settings, this can be wildcarded.

For the Windows build, I also tried that, but with no success to come to a working setup. The Windows build should be fixed in another branch, I think.

>     * is `egor-tensin/setup-mingw` needed if there is `msys2/setup-msys2`?

I had been using that to try to get to a working setup, but without success. It can be omitted.
You can strip the module list in the security settings down to what is actually used and activated in the yml file.

>     * is http_parser changes needed for GA to work? (or can we separate that in another PR)

It came up while reading the logs. I have separated it (Werror on C files) in a separate merge request now. When I saw the warning, I had to find out if there is more warnings due to the compiler version used in the build setup; that's how it sneaked in.

**Comment by mcallegari** [comment]
@hjtappe merged and successfully built!
Thank you very much for your gigantic effort on this PR!
In the next days I'll try to set up also the Windows builds.
Would be awesome to build also the macOS version....but that's probably a real nightmare :rofl:

**Pull request merged**
