### PR TITLE
QML version bumps

### PR DESCRIPTION
**Pull request by mlowczynski**

### CODE REVIEW

**Comment by mcallegari** [comment]
Hey @mlowczynski thanks for this
I'm wondering if it makes sense to actually omit the version number so that the latest version is always imported:
https://doc.qt.io/qt-6/qtqml-syntax-imports.html

**Comment by mlowczynski** [comment]
@mcallegari I have bumped QML module imports to the latest versions supported by Qt5 (5.15 LTS). This makes QML compatible with both Qt5 and Qt6. If the lack of compatibility with Qt5 is no longer a problem for us, it is better to use unqualified module import, as you suggested

**Comment by mlowczynski** [comment]
I think this is a good approach. Do I understand correctly that we can close this PR for now?

**Comment by mcallegari** [comment]
Yeah, it's probably better to submit a new one. Sorry for the change of mind but this is a big change that needs careful attention.

**Comment by mlowczynski** [comment]
No problem

**Pull request closed without merging**
