### PR TITLE
rgbscript: marquee

### PR DESCRIPTION
**Pull request by sandinak**
- adds a marquee function
- has moving "lights" with a count of lights+spaces
- can select the color of the lights
- has fadein depth from outside
- handles corners cleanly so that the lights look even
- tested different sizes on the devtool

### CODE REVIEW

**Comment by sandinak** [comment]
So .. codacy is telling me that using 'var ' on a var is bad form.. and I should be using 'let' .. which makse sense .. however; our code interpreter in qlcplus doth not like 'let ' and in fact throws really.. really annoying error:
`
"marquee.js" Error at line: 99 , column: 7 : "Expected `;', `;'"
`
Which tool me going to dinner and complaining to my duck before i figured out what had changed :) Hope this passes all the rest as I think it's a nice script that we're using on this years show.

**Review by mcallegari — APPROVED** [review]

**Comment by mcallegari** [comment]
Hey can we please close #1301 and #1302 before throwing more stuff on the table? Thanks

**Comment by sandinak** [comment]
Closed the other two .. one was a dupe .. one needs re-write .. this one is ready; but I can't merge because of Coacy.

**Comment by mcallegari** [comment]
Thanks 👍

**Pull request merged**
