### PR TITLE
Update qlcplus_fr_FR.ts

### PR DESCRIPTION
**Pull request by mcallegari**
Completed French Translation
Changed "Appareil" to "Luminaire" too.

### CODE REVIEW

**Comment by mcallegari** [comment]
@Foul thenks for this. Would you mind to update also the ui (v4) translation?

**Comment by Foul** [comment]
Sure.. just point me the right file.. :)

**Comment by mcallegari** [comment]
> This one https://github.com/mcallegari/qlcplus/blob/master/ui/src/qlcplus_fr_FR.ts ? i'm on it ;)

Exactly, yes

**Comment by plugz** [comment]
Sorry I'm late to the party but I think this PR should be reversed.

**Pull request merged**
