### PR TITLE
Qmlui translation de

### PR DESCRIPTION
**Pull request by kripton**
Completes the german translation of the QML UI
Based on the nice work of @fxedel, thanks!

### CODE REVIEW

**Comment by kripton** [comment]
Based on #1077

**Comment by mcallegari** [comment]
Awesome stuff ! Thanks everyone ! :+1:

**Comment by mcallegari** [comment]
@kripton actually you guys haven't rebased on latest master, so German translation is behind 35 strings :cry:

**Comment by kripton** [comment]
You're right, my bad. Fixed in #1098

**Pull request merged**
