### PR TITLE
New fixture - Cameo-LED-Moving-Head-60W-CLMHRGB60W

### PR DESCRIPTION
**Pull request by boxy321**
Original post:

http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8971

Datasheet:

http://www.thomann.de/gb/cameo_moving_head_60.htm

### CODE REVIEW

**Comment by mcallegari** [comment]
Yes it would :)
When the 4.10.0 storm has passed, I could dedicate some time to various pending things

**Comment by boxy321** [comment]
The catalogue (pdf page 5): http://www.cameolight.com/startseite/?force_sid=l0jhu2d9cqktljdpjuem0980e2 shows the same image. However, there are no matching gobos in the library anyway.

**Comment by mcallegari** [comment]
OK, I've had a look and actually we don't have similar matches.
Then there is no solution other than:
- leaving them blank
- ask Cameo to officially provide their gobos. If you want I can send them an email and see if they reply

For now I would go for the first option

**Comment by boxy321** [comment]
You do first. I can do second option???


Sent from my Samsung device

-------- Original message --------

**Comment by mcallegari** [comment]
Let's see if tasaei replies in the forum.
Otherwise leave this to me and I'll sort it out.

**Comment by boxy321** [comment]
👍


Sent from my Samsung device

-------- Original message --------

**Pull request closed without merging**
