### PR TITLE
New fixture and a small fix

### PR DESCRIPTION
**Pull request by McBochi**
Corrected the type of the "ADJ FREQ 16" and added the "ADJ FREQ 5" as a new fixture.

### CODE REVIEW

**Comment by janosvitok** [comment]
Please fix channels vs heads in the new fixture:
- 7 channel mode: channels 6 and 7 should not be included in any head; there should be only 5 heads
- 2 channel mode and 1 channel mode: no head should be defined

**Comment by McBochi** [comment]
Ah, sorry for that - going to fix that!

**Comment by McBochi** [comment]
Quick follow-up question: Got another fixture ready - an RGB PAR-can.
However, the included LEDs can't be controlled separately, so should I even define a single head for all of them?

**Comment by janosvitok** [comment]
if the LEDs are controlled together as one light, don't create a head. Heads are needed only for lights with >= 2 separately controlled parts.

**Comment by mcallegari** [comment]
Physical information missing.
I don't understand why everybody submit fixtures through the forum and you came directly here, despite the message that this is an area for developers

**Pull request merged**
