### PR TITLE
Osc<->serial bridge

### PR DESCRIPTION
**Pull request by agordon**
Hello,

I'd like to suggest this plugin, which will allow sending OSC commands to QLC+ from Arduino without needing networking (UDP) like standard OSC sources.
This patch is done against the `QLC+_4.12.4` tag, and designed in a way to have no code changes at all to any existing QLC code or plugins - hopefully this will make it easier to be accepted.

Full documentation and examples here: https://software.housegordon.com/qlcp-serial-osc-bridge/ (and also included in the second commit of this PR).

### CODE REVIEW

**Comment by agordon** [comment]
I have not tested it on both Linux (Debian 10, x86_64, qt 5.11.3) and Mac OS X (10.11, clang 10, Qt 5.12.12, HomeBrew 3.3.8) - and both worked great.

**Comment by mcallegari** [comment]
Hi, while I appreciate the completeness and usefulness of this plugin, it looks to me like a very custom DIY project.
It requires users to build their own controller and I doubt everyone is capable of doing it.
I suggest to keep this plugin as a separate project on your Github repository and reference it in the QLC+ website, so users know about it and can download pre-built so/dll/dylib that you will provide.
Sounds good to you?

**Comment by agordon** [comment]
@mcallegari 
It's certainly your decision in the end.

I would argue that advanced QLC+ users have been creating their own custom hardware for a while, e.g.:
https://www.qlcplus.org/forum/viewtopic.php?t=10895
https://mdspitteler.com/projects/midi-dmx-controller-with-qlc/
http://www.qlcplus.org/forum/viewtopic.php?t=12133
https://www.reddit.com/r/lightingdesign/comments/izn97k/i_have_made_a_midi_controller_to_control_my/

And most of them have to resort to complicated Arduino/Usb/Midi setup to emulate midi device, e.g.:
http://www.qlcplus.org/forum/viewtopic.php?t=14337
https://www.qlcplus.org/forum/viewtopic.php?t=12690
https://forum.arduino.cc/t/need-simple-guidance-on-sending-a-midi-command/596852

This plugin actually makes things simpler - no more need for any midi emulation, and does not invent any new protocols.

Since the entire code for the arduino microcontroller is included in the documentation of this plugin, any beginner "maker" who can use arduino on a breadboard can use it.

I would also think this is very "low risk" since I purposefully did not modify a single line of code in the rest of QLC+ - so regressions are impossible :)

regards,
assaf gordon

**Comment by mcallegari** [comment]
@agordon  I'm perfectly aware of "advanced DIY" users, but they represent the minority of the QLC+ user base, which counts several thousands of people.
I would argue also on the fact that "not touching a single line of code" is "low risk". When you will disappear at some point (everybody do in open source) I will have to maintain your code: e.g. make it build with newer compilers, adjust the code if I need new plugin interfaces and so on.

I have nothing against you or your code. As I said before, it is well done, but speaking with the past experiences and considering my spare time is limited, I prefer to keep this as a side project maintained by you.
Again, I am willing to reference it from the QLC+ website so people know about its existence.

**Comment by mcallegari** [comment]
No feedback. Closing.

**Pull request closed without merging**
