### PR TITLE
Rgbscripts strobe

### PR DESCRIPTION
**Pull request by chrisderock**
a small improvement for strobe.js to set a frequency for the strobe. with this you cannot only blink every second step. you can define "blink on every Xth step". Also changed the big if-else-block to a simple one-liner

### CODE REVIEW

**Comment by mcallegari** [comment]
Please have a look at the other scripts with parameters.
Frequency should be a member of algo.
Example: https://github.com/mcallegari/qlcplus/blob/master/resources/rgbscripts/circles.js#L32

**Comment by chrisderock** [comment]
The first try was with algo.frequency but codacity mentioned errors. can you give me a hint how to avoid errors like "foo[key] = falue; is not allowed"?

**Comment by chrisderock** [comment]
seems that i found a way to avoid map[key] ;)

**Comment by mcallegari** [comment]
I wouldn't bother Codacy that much in this case.
We're not dealing with pages of a public website and Codacy JS linter is made for that.

**Comment by chrisderock** [comment]
i know. but if i can avoid such an error i do that ;)

**Pull request merged**
