### PR TITLE
Pull in QT WebSocket library for parsing

### LINKED ISSUE #1308: A crash when using the Web interface
I was playing around with the Web interface and after pressing lots of buttons, qlcplus crashed (SIGABRT from a failed assertion). It appears to be random, but I was able to eventually reproduce the crash inside gdb:

```
[Thread 0x7fffeb7fe640 (LWP 45970) exited]
ASSERT: "uint(i) < uint(size())" in file /usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h, line 500

Thread 1 "qlcplus" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737260009536) at pthread_kill.c:44
44	pthread_kill.c: No such file or directory.
(gdb) backtrace
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737260009536) at pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737260009536) at pthread_kill.c:80
#2  __GI___pthread_kill (threadid=140737260009536, signo=signo@entry=6) at pthread_kill.c:91
#3  0x00007ffff65fc476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff65e27b7 in __GI_abort () at abort.c:79
#5  0x00007ffff6aa3ba3 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff6aa2ff0 in qt_assert_x(char const*, char const*, char const*, int) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff7e28044 in QByteArray::at(int) const (this=0x7fffffffdf90, i=2) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h:500
#8  0x00007ffff7677a83 in QHttpConnection::webSocketRead(QByteArray) (this=0x7fff18003360, data=...) at qhttpserver/qhttpconnection.cpp:440
#9  0x00007ffff7676419 in QHttpConnection::parseRequest() (this=0x7fff18003360) at qhttpserver/qhttpconnection.cpp:129
#10 0x00007ffff76a2f7f in QHttpConnection::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_o=0x7fff18003360, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7fffffffe0c0) at moc_qhttpconnection.cpp:118
#11 0x00007ffff6d03a88 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff576502f in  () at /lib/x86_64-linux-gnu/libQt5Network.so.5
#13 0x00007ffff5778359 in  () at /lib/x86_64-linux-gnu/libQt5Network.so.5
#14 0x00007ffff70dc6b3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff6ccc16a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff6d26155 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff4f1a8bb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff4f6df08 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff4f18003 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff6d25548 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff6ccaa9b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff6cd3024 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x0000555555559fc8 in main(int, char**) (argc=6, argv=0x7fffffffe718) at main.cpp:400
```

System is Ubuntu 21.10, Linux kernel 5.13.0-22-generic x86_64, Qt 5.15.2

The line of code in question appears to be: https://github.com/mcallegari/qlcplus/blob/66069180c4d60d415114849077ffbf28613b212b/webaccess/src/qhttpserver/qhttpconnection.cpp#L440

### PR DESCRIPTION
**Pull request by awwright**
This avoids crashes when frames arrive in separate TCP packets.

---

This is an alternative to #1335 and closes #1308. It pulls in the official Qt parser, which is otherwise a private API.

This is the output from a websocket test suite, [index.html.pdf](https://github.com/mcallegari/qlcplus/files/8782709/index.html.pdf). The failed cases 1.1.6/1.1.7/1.1.8/1.2.6/1.2.7/1.2.8 are testing packet lengths that are too big, and the Qt code responds appropriately with response code 1009.

(To get it to work with the test suite, you have to slightly modify the code to echo back complete messages, see the following patch.)

```diff
diff --git a/webaccess/src/qhttpserver/qhttpconnection.cpp b/webaccess/src/qhttpserver/qhttpconnection.cpp
index 806a8f219..2549dde70 100644
--- a/webaccess/src/qhttpserver/qhttpconnection.cpp
+++ b/webaccess/src/qhttpserver/qhttpconnection.cpp
@@ -362,6 +362,8 @@ QHttpConnection *QHttpConnection::enableWebSocket()
         this, SLOT(slot_pingReceived(const QByteArray&)));
     connect(m_webSocketParser, SIGNAL(textMessageReceived(const QString&)),
         this, SLOT(slot_textMessageReceived(const QString&)));
+    connect(m_webSocketParser, SIGNAL(binaryMessageReceived(const QByteArray&)),
+        this, SLOT(slot_binaryMessageReceived(const QByteArray&)));
     connect(m_webSocketParser, SIGNAL(errorEncountered(QWebSocketProtocol::CloseCode, const QString)),
         this, SLOT(slot_closeReceived(QWebSocketProtocol::CloseCode)));
     connect(m_webSocketParser, SIGNAL(closeReceived(QWebSocketProtocol::CloseCode, const QString)),
@@ -398,6 +400,11 @@ void QHttpConnection::webSocketWrite(WebSocketOpCode opCode, const QByteArray &d
     }
 }
 
+void QHttpConnection::slot_binaryMessageReceived(const QByteArray &data)
+{
+    webSocketWrite(BinaryFrame, data);
+}
+
 void QHttpConnection::slot_pingReceived(const QByteArray &data)
 {
     webSocketWrite(Pong, data);
@@ -405,6 +412,7 @@ void QHttpConnection::slot_pingReceived(const QByteArray &data)
 
 void QHttpConnection::slot_textMessageReceived(const QString &data)
 {
+    webSocketWrite(TextFrame, data.toUtf8());
     Q_EMIT webSocketDataReady(this, data);
 }
 
diff --git a/webaccess/src/qhttpserver/qhttpconnection.h b/webaccess/src/qhttpserver/qhttpconnection.h
index cca596a59..100c40c64 100644
--- a/webaccess/src/qhttpserver/qhttpconnection.h
+++ b/webaccess/src/qhttpserver/qhttpconnection.h
@@ -109,6 +109,7 @@ Q_SIGNALS:
 private Q_SLOTS:
     void slotWebSocketPollTimeout();
     void slot_pingReceived(const QByteArray &data);
+    void slot_binaryMessageReceived(const QByteArray &data);
     void slot_textMessageReceived(const QString &data);
     void slot_closeReceived(QWebSocketProtocol::CloseCode closeCode);
```

### CODE REVIEW

**Comment by awwright** [comment]
3da306527 is pulled from Qt 5.15.2 and appears to use some API features too new for 5.14.2... Let's try downgrading to 5.15.0 before `QStringView::toInt` was introduced and see if that fixes the build

**Comment by mcallegari** [comment]
@awwright  please see my last comment on #1308 
What you're experiencing with this build is exactly what I'm talking about.
Let's avoid it...

**Comment by awwright** [comment]
@mcallegari I see—sorry, I thought I was trying something new by copying in the sources. However, I was able to get much further in just a couple hours of work, compared to #1335. I tried this because when I was running the tests on #1335 there were still more than a few failures that could plausibly cause data corruption or some other problems in the future. I can provide the test results if you're interested.

Maybe you can still take a look at this, I seem to have everything working. There's just one error from the code analysis tool that can probably be ignored.

**Comment by awwright** [comment]
@mcallegari There seems to be an error with the AppVeyor builds in general (was there a system change?), but otherwise it should pass, and I think this is ready for your consideration. The Codacy analysis shows one type of error ("Check buffer boundaries") which can be ignored: in all the cases the code has already checked the buffer boundary using `bytesAvailable`. Please see https://github.com/mcallegari/qlcplus/issues/1308#issuecomment-1140605478 for a comparison of the solutions I've tried.

**Comment by awwright** [comment]
@mcallegari This PR is ready for your consideration, could you please take a look? The only remaining error is the code analysis wants read() calls to check the return value, which it is doing.

**Comment by mcallegari** [comment]
As I mentioned [here](https://github.com/mcallegari/qlcplus/issues/1308#issuecomment-1138291924) a month ago, I'm not sure if I want to drag in another Qt dependency to the project.
I'd prefer to fix the current implementation as, thanks to your analysis, it seems the issue to fix is a corner case reported basically only by you.
I could spend some time to reproduce the issue and attempt a fix myself without extra dependencies.

**Comment by awwright** [comment]
@mcallegari I'm hoping to submit a number of other improvements to the Web interface, especially around tempo, and even with the simple fixes that prevents crashing, the test suite still flagged a number of other issues that will likely cause problems, see [qlc+-websocket-parsing.pdf](https://github.com/mcallegari/qlcplus/files/8794871/qlc%2B-websocket-parsing.pdf).

We could write code that fixes all of those problems, but it would not be as quick to implement, or easy to maintain, as copying in an existing parser. No dependencies have been added, it uses the same public Qt API that the rest of QLC+ uses.

I spent several days on #1335; I was able to finish this PR in a couple hours. In my testing, everyone who uses Wi-Fi is affected.

**Comment by awwright** [comment]
@mcallegari Can you please merge this? It doesn't add any dependencies.

**Pull request closed without merging**
