### PR TITLE
a better widget delete dialog if a widget has no label

### PR DESCRIPTION
**Pull request by sammuell**

### CODE REVIEW

**Comment by mcallegari** [comment]
First, it's a good practice to explain a change, not just throw it.
At least reference a forum discussion or a github ticket.
Second, you haven't followed the code convention used in other thousands lines of code.
https://github.com/mcallegari/qlcplus/wiki/Coding-guidelines

This is not the way to contribute.

**Comment by sammuell** [comment]
For the reference, here's the associated thread in the forum: https://www.qlcplus.org/forum/viewtopic.php?f=35&t=14070

**Comment by mcallegari** [comment]
Thanks

**Comment by mcallegari** [comment]
@sammuell Actually, the guy is right
https://www.qlcplus.org/forum/viewtopic.php?f=18&t=14138

I think it's better to separate with "<br>" (not sure if "\n" will work)

**Pull request merged**
