### PR TITLE
Add Shehds 200W LED COB Blinder

### PR DESCRIPTION
**Pull request by Devsider**
Added Shehds 2 Eyes 200W LED COB Blinder. Both 4 and 8 Channel Modes.

### CODE REVIEW

**Comment by mcallegari** [comment]
This fixture is not valid.
Please either fix it or submit it in the forums
https://www.qlcplus.org/forum/viewforum.php?f=3

**Comment by Devsider** [comment]
> This fixture is not valid. Please either fix it or submit it in the forums https://www.qlcplus.org/forum/viewforum.php?f=3

Honestly i cant figure out what whould be wrong with it, QLC+ takes the file just fine and it was created with the original qlc+4 fixture editor, no external editing other than the typo. Github Actions error messages weren't too helpful either.

**Comment by mcallegari** [comment]
When you come directly to GitHub, it's basically implicit that you've read all the necessary information how to submit a fixture definition.
If you read this: 
https://www.qlcplus.org/forum/viewtopic.php?t=6667
You will find that a fixture validator exists:
https://www.qlcplus.org/fixture_validator.php
And it will tell you the errors you've made.

**Comment by Devsider** [comment]
Sorry for the inconveniences. I fixed the issues, both fixture files validate fine now. 
image
image

**Comment by mcallegari** [comment]
While [Shedhs](https://shehds.com/) has a website, can you please share the product page of the Somspot fixture?
If it is a no-brand chinese product, withou product page or a manual, then I won't drag it into QLC+, sorry.

**Comment by Devsider** [comment]
I believe Somspot only sells though AliExpress, they don't have a website. They sell quite a large amount out different fixtures with solid quality. Manuals are provided printed with the product, I have a scanned PDF of it, which I could provide if needed. 

Product Page:
https://a.aliexpress.com/_Ez6OV1V

Somspot AliExpress Store:
https://a.aliexpress.com/_EG2t61D

**Comment by mcallegari** [comment]
Please remove the Somspot fixture.

**Comment by mcallegari** [comment]
Merged with errors.
Next time please submit via forums. Thanks
Product page: https://shehds.com/products/shehds-2eyes-200w-led-cob-blinder-cool-white-warm-white-lighting-p0217
Manual: https://drive.google.com/file/d/1K0H8CoFUJ_ob2MJ2JmaJ7ulSAXMqCmTG/view

**Pull request merged**
