### PR TITLE
New fixture - Robe ClubWash 600 CT

### PR DESCRIPTION
**Pull request by boxy321**
Created on 06/09/15

Nearly every capability did not match the datasheet in some way so all had to be changed from the original post:

http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8884
http://www.robe.cz/it/support/list-files/15/file-detail/4509/file-cat/robe-downloads/

### CODE REVIEW

**Comment by mcallegari** [comment]
And this is fixture number 600 ! Yay ! :smiley:

**Comment by boxy321** [comment]
Wow! Sorry about the earlier descrepancies. Some definitions are awful and it's like starting from scratch.

**Comment by mcallegari** [comment]
Ouch, I've deleted my comment cause we're not at 600 yet, sorry.
Just one more to go !

**Comment by mcallegari** [comment]
> Wow! Sorry about the earlier descrepancies. Some definitions are awful and it's like starting from scratch.

Yeah, I know. Sometimes people just share crap that seems fine to them :(

**Pull request merged**
