### PR TITLE
Maintenance presets

### PR DESCRIPTION
**Pull request by kluszon**
Added maintenance presets as discussed in topic: https://www.qlcplus.org/forum/viewtopic.php?f=35&t=14102&p=59018#p59018

It'll be good to increase QXF version after this changes.

### CODE REVIEW

**Comment by mcallegari** [comment]
Hi, thanks. Should I wait for the definitions review?

> It'll be good to increase QXF version after this changes.

Not really, no. QLC+ is always consistent with the provided fixture library.
If you used QLC+ fixture library to make a commercial product, then it's another story...

**Comment by kluszon** [comment]
> Hi, thanks. Should I wait for the definitions review?
> 
> > It'll be good to increase QXF version after this changes.
> 

Are you talking about fixtures definition review?

> Not really, no. QLC+ is always consistent with the provided fixture library.
> If you used QLC+ fixture library to make a commercial product, then it's another story...

Ok, I understand.

**Comment by mcallegari** [comment]
> > Hi, thanks. Should I wait for the definitions review?
> 
> Are you talking about fixtures definition review?

Of course! Aren't we talking about fixtures here? 😉

**Comment by kluszon** [comment]
> > > Hi, thanks. Should I wait for the definitions review?
> > 
> > 
> > Are you talking about fixtures definition review?
> 
> Of course! Aren't we talking about fixtures here?

Yes :) You can publish a new version of qlc+ with fixture editor and we'll add updated fixtures library as soon as possible.

**Comment by mcallegari** [comment]
Someone at work taught me that "as soon as possible" means absolutely nothing. ASAP could mean "in 10 years".
I won't accept this change unless there is a real usage case for it. Otherwise it's just more unused code.

**Comment by kluszon** [comment]
OK, as you wish... We started work on it, but it's lots of work, so it can take some time.

**Comment by kluszon** [comment]
> Someone at work taught me that "as soon as possible" means absolutely nothing. ASAP could mean "in 10 years".
> I won't accept this change unless there is a real usage case for it. Otherwise, it's just more unused code.

We modified 541 fixtures. We added maintenance presets, fixed missing capability preset in groups and fixed other found bugs. Can we merge it now?

**Comment by mcallegari** [comment]
This is not a good quality job. I spent 30 seconds and then I stopped

- there are git conflicts and this cannot be merged anyway
- `resources/file.patch` is not wanted and you left it there
- `resources/fixtures/ADB/ADB-Warp-M.qxf` just a change a version. I don't want that. I want to keep the original version of the submitter
- `resources/fixtures/AVE/AVE-Quad-Pro-Flat.qxf` who told you that "No function" is "LampOff"?
- `resources/fixtures/American_DJ/American-DJ-12P-Hex.qxf` "No strobe" is NOT "StrobeRandom"

Then I stopped.
I won't waste my time on this.

**Comment by kluszon** [comment]
Ok, I removed the last commit and I'm working on a fix for those points.

> This is not a good quality job. I spent 30 seconds and then I stopped
> 
> * there are git conflicts and this cannot be merged anyway

I'll check it.

> * `resources/file.patch` is not wanted and you left it there

Yes, it's my fault. It'll be removed.

> * `resources/fixtures/ADB/ADB-Warp-M.qxf` just a change a version. I don't want that. I want to keep the original version of the submitter

Yes, I agree that in this case modification change only a file version, but in older fixtures, resave file in the new fixture editor is updating file structure with preset what is good. From my point of view, it'll be much better to have updated all fixtures to the newest version. Finally, it's your decision.

> * `resources/fixtures/AVE/AVE-Quad-Pro-Flat.qxf` who told you that "No function" is "LampOff"?

Ok, I'm going back with these changes.

> * `resources/fixtures/American_DJ/American-DJ-12P-Hex.qxf` "No strobe" is NOT "StrobeRandom"

The same here.

**Comment by kluszon** [comment]
We have been discussing your feedback and would like to suggest adding NoStrobe and NoFunction presets. The first reason for this is it standardizes the capability rather than community member entering a mixture "No Strobe", "No strobe", "nostrobe", "Strobe Off" etc... It also enables you to add a clear function which sets all groups to a capability where the device is not strobing or zooming. This is a standard function on most consoles and lighting software and is used before programming a new scene.

**Comment by mcallegari** [comment]
What the users write in the capability description is now irrelevant, thanks to presets.
"strobe off" is already there and it's called ShutterClose or ShutterOpen, since strobe is normally achieved with a shutter.
In case of digital strobe, users just need to set the preset to ShutterOpen.

**Comment by joshuaurieli** [comment]
Hello @mcallegari, I am working on the fixture files with @kluszon. If I understand your comment correctly:

For capabilities in "Shutter" group:

- Description "**strobe off**" should have Preset="**ShutterOpen**" (if the fixture has no intensity capability, then Preset="**ShutterClose**" )
- Description "**no strobe**" should have Preset="**ShutterOpen**" (if the fixture has no intensity capability, then Preset="**ShutterClose**" )
- Description "**no function**" should have Preset="**ShutterOpen**"  (if the fixture has no intensity capability, then Preset="**ShutterClose**" ) because "no function" is often used in "Shutter" groups instead of "no strobe" e.g. fixtures\American_DJ\American-DJ-Galaxian-Gem-IR.qxf
- Description "**LED on**" should have Preset="**ShutterOpen**" because this is a digital strobe
- Description "**on**" should have Preset="**ShutterOpen**" because this is a digital strobe
- Description "**LED off**" should have Preset="**ShutterClose**" because this is a digital strobe
- Description "**off**" should have Preset="**ShutterClose**" because this is a digital strobe

And of course

- Description "**Shutter close**" should have **ShutterClose**
- Description "**Shutter open**" should have **ShutterOpen**

By, for instance "no strobe", I mean all variations of "no strobe", "No strobe", "No Strobe", "nostrobe", etc...

**Comment by mcallegari** [comment]
Let's take a step back.
Do you know what a shutter is? And how the strobe effect is typically achieved in traditional moving heads?
From your comments it doesn't seem you do. Strobe has nothing to do with the intensity channel.

**Comment by joshuaurieli** [comment]
Thank you for your question. Good idea.

There are two ways that a strobe effect is achieved. In a traditional moving head there is an intensity source that is controlled by the intensity channel and a shutter (a small piece of metal that stops the light shining from the device). Strobe effects are achieved by opening and closing the shutter. Which means the shutter and intensity independent. 

In a modern moving head with an led source, or in a dedicated strobe fixture there is no mechanical shutter. Strobe effects are achieved by turning the light source on and off. Intensity may or may not be regulated by setting how bright the light source is when it is on.

The problem is, this makes it unclear what exactly "No Strobe", "Strobe Off" or "No Function" means:
Does it mean that the intensity source is controlled independently and the shutter has been opened ("ShutterOpen").
Does it mean that the light source itself has been turned off ("ShutterClose")

My suggestion was to base this distinction on the existence of an intensity channel. However, perhaps I was mistaken and this distinction is unnecessary. Then we can make every instance of "No Strobe", "Strobe Off" or "No Function" in a shutter group simply "ShutterOpen"

**Comment by mcallegari** [comment]
OK, now we're talking the same language :smile: 

In general, fixtures with a mechanical shutter, will explicitly indicate the shutter state as in "Shutter open" or "Shutter close". For these, the presets are clear.

In case of digital strobe or "vague" indications, "strobe off" or "no strobe" or "no function" usually means "ShutterOpen", because there is no shutter at all.
Since QLC+ 5 tries to simulate as much as possible the physical features of a fixture, there is no "StrobeOff" preset, instead I decided to base the preview on the presence of a shutter. Also because the strobe feature is always in a "Shutter" type channel. :wink: 

To conclude, and to be clear, you can have intensity at 80%, red color set, but if the shutter is closed, the QLC+ preview will show no light at all, as it happens in the real world. You can try it yourself with QLC+ 5.
If in a definition, someone put "ShutterClose" for "no strobe", it will be considered an error (and they will see no light at all)

**Comment by joshuaurieli** [comment]
Thank you for the explanation, the approach makes sense.

I have one more point to clarify. There are some American DJ fixtures with a digital shutter. E.g.  American-DJ-Mega-Hex-Par.qxf

```
<Group Byte="0">Shutter</Group>
<Capability Min="0" Max="31">LED off</Capability>
<Capability Min="32" Max="63">LED on</Capability>
<Capability Min="64" Max="95">Strobing slow - fast</Capability>
<Capability Min="96" Max="127">LED on</Capability>
<Capability Min="128" Max="159">Strobe pulse slow - fast</Capability>
<Capability Min="160" Max="191">LED on</Capability>
<Capability Min="192" Max="223">Random strobe slow - fast</Capability>
<Capability Min="224" Max="255">LED on</Capability>
```

Here it makes sense to use **ShutterClose** in the case of **LED off** because it represents how the devices digital shutter will stop the fixture producing any light at all.

```
<Capability Min="0" Max="31" Preset="ShutterClose">LED off</Capability>
<Capability Min="32" Max="63" Preset="ShutterOpen">LED on</Capability>
<Capability Min="64" Max="95" Preset="StrobeSlowToFast">Strobing slow - fast</Capability>
<Capability Min="96" Max="127" Preset="ShutterOpen">LED on</Capability>
<Capability Min="128" Max="159" Preset="PulseSlowToFast">Strobe pulse slow - fast</Capability>
<Capability Min="160" Max="191" Preset="ShutterOpen">LED on</Capability>
<Capability Min="192" Max="223" Preset="StrobeRandomSlowToFast">Random strobe slow - fast</Capability>
<Capability Min="224" Max="255" Preset="ShutterOpen">LED on</Capability>
```

Is this interpretation in line with your approach?

**Comment by mcallegari** [comment]
> Here it makes sense to use ShutterClose in the case of LED off because it represents how the devices digital shutter will stop the fixture producing any light at all by overriding the intensity channel and stopping the LED from turning on.

Correct. Basically they're simulating shutter open/close with LED on/off, so your interpretation is correct.

**Comment by kluszon** [comment]
@mcallegari Sorry, I can't resolve conflicts, because I haven't got write access to the repository.

**Comment by mcallegari** [comment]
I cannot merge a pull request if there are conflicts.
You should rebase (google: git rebase) your branch with the upstream sources.

**Comment by kluszon** [comment]
> I cannot merge a pull request if there are conflicts.
> You should rebase (google: git rebase) your branch with the upstream sources.

Done

**Comment by mcallegari** [comment]
Merged, thanks :+1:

**Comment by joshuaurieli** [comment]
@mcallegari Thank you for merging the changes and fixing the issues! I am sorry about the errors you encountered. I have looked at c1badb7 and noted the following two errors:

- White space error:  `<Capability Min="0" Max="15"Preset="ShutterOpen">Off</Capability>`
- Physical properties not filled out:
 ```
 <Bulb Type="" Lumens="0" ColourTemperature="0"/>
  <Dimensions Weight="0" Width="0" Height="0" Depth="0"/>
  <Lens Name="Other" DegreesMin="0" DegreesMax="0"/>
  <Focus Type="Fixed" PanMax="0" TiltMax="0"/>
  <Technical PowerConsumption="0" DmxConnector="5-pin"/>
```

I have added these two cases to our pull request check-list to ensure they will not occur again. Were there any other errors you came across?

**Comment by mcallegari** [comment]
Yes, see 4aed28bfa26887438b29b461412321c01aef2f2a

- the most serious: you renamed some fixtures. WHY?? Do you realize that if some users are using those fixtures and you rename them, you will break their projects??
- You re-added one fixture I deleted (Chauvet Intimidator 355Z)
- You added generic fixtures, all useless and all without physical information. How can QLC+ preview fixtures with width,height,depth equal to 0??
- You added a Brighter fixture with empty physical dimensions
- You added a Martin fixture very incomplete

This is exactly the mess I wanted to avoid.
The lack is basically your poor knowledge of git (re-adding a deleted file means you're not in sync with upstream) and that you included off-topic changes.
If the Pull Request is named "maintenance presets", why do you add new fixtures in between?
You should have separated new fixtures into a new pull request. Easier to discuss and review.

My fault too. Next time I will spend more time to review your pull requests and keep on rejecting them until they're up to standards.

**Comment by joshuaurieli** [comment]
OK. Thank you for listing the errors, we will go through them and make sure they don't happen again. We will also review how we are using Git, the merge took way too much time on our side as well... Thanks again for fixing the errors.

**Pull request merged**
