### PR TITLE
Fixturemanager fixes

### PR DESCRIPTION
**Pull request by offtools**
Hi,

(I moved my fixturemanager fixes into a separate PR, not longer in softpatcheditor PR)

PR fixes simpledesk issues on changing the universe of a fixture in the fixturemanager and wrong entries in doc::m_addresses.

fixturemanager:1273 m_doc->moveFixture(id, af.address()); ignored universe and caused wrong entries in m_addresses

doc.cpp:525 int address = fixture->address(); ignored universe and caused wrong entries in m_addresses

*fixturemanager updates  view directly after changing the fixture
*simpledesk shows the correct fixtures in the different universes
*removed functions, which are not really necessary anymore (moveFixture, changeFixtureMode)

### CODE REVIEW

**Comment by plugz** [comment]
Hi,

I'm examining the change.

For the sake of history clarity, could you make this PR only one commit ? Looks like a8c6d42 is the only one useful.

Thanks :)

**Comment by plugz** [comment]
Looks good to me. Rebased on master, and changed some minor things (here #475)

Is #475 good to you ?

**Comment by mcallegari** [comment]
As discussed before, e9d42fe3a6ce12cf043737841e5d3fe821de74ff is not good for me.

@plugz is #475 equivalent to this PR or something else ?

**Comment by plugz** [comment]
Yes, #475 is equivalent to this PR. This is bugfix-only, no other change.

I opened #475 to avoid merging 6 commit, from which only one actually does something. And I cleaned up some stuff too.

**Comment by plugz** [comment]
merged as #475 , thanks :)

**Pull request closed without merging**
