### PR TITLE
RGB Script which alternates exactly between two halfs

### PR DESCRIPTION
**Pull request by DrFreas**
Splits a Matrix in half and alternates between both halfs, vertically or horizontally.

### CODE REVIEW

**Comment by hjtappe** [comment]
Can this already be achieved by setting the blocksize in the alternate.js script? Would it make sense to extend that one or is it reflecting another use-case?

**Comment by DrFreas** [comment]
I also saw the alternate.js script, but the block size is limited to 16, as far as I see it. This script here would simply divide a matrix in two halfs, regardless of size. Also at least I use it for live shows where I choose the effects from the RGB-effect widget thingy and setups change frequently, so I won't have to worry about any parameters I would have to set to adapt.

**Comment by mcallegari** [comment]
To be honest I would extend the alternate.js script with a new parameter like "divide in halves"
Too many scripts with similar purposes would create confusion

**Comment by mcallegari** [comment]
Addressed by #1414

**Pull request closed without merging**
