### PR TITLE
Implemented catching sliders feature

### PR DESCRIPTION
**Pull request by siegmund42**
As requested here: http://www.qlcplus.org/forum/viewtopic.php?f=18&t=10814&p=46597#p46597
It would be great if sliders could be "caught" by external controls, if they have no motor faders.

I tried to implement this. It depends on if there is a feedback patched to the universe - if not, the new behavior is applied.
To catch the slider, simply move the external control to the current level of the slider and the slider will follow your external control as soon as you reached a certain area around the current level with your external control.

There is one drawback: If you move very fast across the current value, the slider might not be caught, but I wouldn't consider this is a big problem.

### CODE REVIEW

**Comment by siegmund42** [comment]
Works well with a BCF 2000.
With the last commit, drawback when moving fast across the value is resolved.

**Comment by xhpohanka** [comment]
Hi,
I was again around qlc and noticed that this PR has not been merged yet. Is there any problem here? I would really appreciate this function...

thanks all

**Comment by siegmund42** [comment]
Since someone has again requested this feature [here](http://www.qlcplus.org/forum/viewtopic.php?f=33&t=11658&p=50004#p50004) I would like to dig this up. I think there are a lot of users who would be happy to see that feature (at least from 4 I know).
I'm happy to change the PR to resolve conflicts or other issues if you are willing to merge.

**Comment by mcallegari** [comment]
@siegmund42  Implemented my way: 29ec50d51fca1cec6c9a978ac587c2670593d090
It has less impact than your patch. Please check if everything is OK. 
I'll leave this open for discussion until the feature is OK.

**Comment by siegmund42** [comment]
Thanks for the repsonse! I replied in the [forum thread](http://www.qlcplus.org/forum/viewtopic.php?f=33&t=11658&p=50072#p50072), there may be some issues left.

**Comment by mcallegari** [comment]
@siegmund42 thanks for the loopback example
I think I've fixed the remaining cases here 3e556d0fc116bb60170926918c067c2c4f22773e
The problem was the 'surpassing' case (for fast values change) that did not consider page switch (show/hide) and disable state.
Please check if everything is fine now, thanks

**Comment by siegmund42** [comment]
Thank you for fixing! Seems to work fine now - closing.
Thanks again, I'm sure there will be lots of users who are appreciating this!

**Pull request closed without merging**
