### PR TITLE
Engine - script - startDetached() enables to delete QProcess object without killing running process

### PR DESCRIPTION
**Pull request by Thierry-d**
Hello Massimo,

Here is a very simple fix for [#1270](https://github.com/mcallegari/qlcplus/pull/1270) and[ #1339](https://github.com/mcallegari/qlcplus/issues/1339) 

Replacing start() by startDetached() enables to immediately delete the QProcess object, and clean-up all associated pipes and file descriptors, without killing the running process.

This fix has been validated:
- on Linux Raspbian 10 with Qt 5.11.3
- and on Windows 10 with Qt 5.15.3

This fix does not drastically change the current behavior of system commands, unlike the fix on procfix which requires to specify a timeout (wait time) for every command. 

This fix is based on following doc & source code of QProcess::startDetached :
- https://www.qt.io/blog/2017/08/25/a-new-qprocessstartdetached
- https://doc.qt.io/qt-5/qprocess.html#startDetached

- https://github.com/qt/qtbase/blob/5.15/src/corelib/io/qprocess.cpp
- https://github.com/qt/qtbase/blob/5.15/src/corelib/io/qprocess_unix.cpp
- https://github.com/qt/qtbase/blob/5.15/src/corelib/io/qprocess_win.cpp

My test results on Linux & Windows are summarized below:

1) The number of open file descriptors does not increase anymore every time a new systemcommand is executed.

On Linux: ls -l /proc/`pidof qlcplus`/fd | wc -l
28

On Windows: handle -s -p qlcplus | find "File"
  File            : 47

2) The standard input/output/error streams (0, 1, 2) of the sub-processes launched by systemcommand are inherited from qlcplus and redirected to the same devices as qlcplus (no change):

ls -l /proc/1929/fd
total 0
lr-x------ 1 pi pi 64 Aug 20 10:250 -> /dev/null
l-wx------ 1 pi pi 64 Aug 20 10:25 1 -> /home/pi/.cache/lxsession/LXDE-pi/run.log
l-wx------ 1 pi pi 64 Aug 20 10:25 2 -> /home/pi/.cache/lxsession/LXDE-pi/run.log

ls -l /proc/$(pidof qlcplus)/fd
total 0
lr-x------ 1 pi pi 64 Aug 20 10:22 0 -> /dev/null
l-wx------ 1 pi pi 64 Aug 20 10:22 1 -> /home/pi/.cache/lxsession/LXDE-pi/run.log
lrwx------ 1 pi pi 64 Aug 20 10:22 10 -> 'socket:[24384]'
lrwx------ 1 pi pi 64 Aug 20 10:22 11 -> /dev/snd/seq
lrwx------ 1 pi pi 64 Aug 20 10:22 12 -> 'socket:[24386]'
lr-x------ 1 pi pi 64 Aug 20 10:22 13 -> 'pipe:[24387]'
l-wx------ 1 pi pi 64 Aug 20 10:22 14 -> 'pipe:[24387]'
lr-x------ 1 pi pi 64 Aug 20 10:22 15 -> 'pipe:[24388]'
l-wx------ 1 pi pi 64 Aug 20 10:22 16 -> 'pipe:[24388]'
lrwx------ 1 pi pi 64 Aug 20 10:22 17 -> 'anon_inode:[timerfd]'
lr-x------ 1 pi pi 64 Aug 20 10:27 18 -> 'pipe:[24389]'
l-wx------ 1 pi pi 64 Aug 20 10:27 19 -> 'pipe:[24389]'
l-wx------ 1 pi pi 64 Aug 20 10:22 2 -> /home/pi/.cache/lxsession/LXDE-pi/run.log
…

3) All system commands keep running as long as needed, independantly from qlcplus.

### CODE REVIEW

**Comment by mcallegari** [comment]
Hi, thanks for this.
This is really curious because I'm convinced I already tried the detached way and it didn't work for me.
Can you please tell me which system command you tried?

**Comment by Thierry-d** [comment]
Hello Massimo,

I tested the 3 following scripts:
- on Linux:
systemcommand:/usr/bin/sleep arg:10000
- on Windows:
systemcommand:"C:\Windows\explorer.exe"
systemcommand:"C:\Windows\System32\cmd.exe"

I'm more than happy to test other commands if it can help.
Thierry

**Comment by mcallegari** [comment]
Thanks. So the sleep on Linux starts a detached process and after 10 seconds it ends properly and leave no PID trace?

**Comment by Thierry-d** [comment]
On Linux, "ps" is showing that the parent process id (PPID) of all system commands (/usr/bin/sleep) started by qlcplus is 1. This confirms the system commands are detached from qlcplus.
pi        1409  1062  1 20:47 ?        00:00:19 /usr/bin/qlcplus
pi        1447     1  0 20:48 ?        00:00:00 /usr/bin/sleep 10000
pi        1469     1  0 20:51 ?        00:00:00 /usr/bin/sleep 10000
pi        1481     1  0 20:52 ?        00:00:00 /usr/bin/sleep 10000
pi        1483     1  0 20:52 ?        00:00:00 /usr/bin/sleep 10000
pi        1485     1  0 20:52 ?        00:00:00 /usr/bin/sleep 10000

And whatever the number of (simultaneous or sequential) commands launched by qlcplus, the memory usage of qlcplus is stable, as well as the number of fd's:
$ pmap -p 1409 | grep total
 total   339260K
$ ls -l /proc/1409/fd | wc -l
28

I also tested shell scripts writing to ttys or files (eg "systemcommand:/usr/bin/bash arg:/home/pi/hello-world"). No issue at all.

**Comment by mcallegari** [comment]
Merged, thanks a lot :+1:

**Pull request merged**
