### PR TITLE
Fixtures: Add XStatic X-240 LED Bar

### PR DESCRIPTION
**Pull request by nedmech**

### CODE REVIEW

**Comment by mcallegari** [comment]
Hi Nathan, thanks but I've got a few comments:

1- this PR includes also a RGB script. Next time, please create separate pull requests for each file
2- when submitting a new fixture it is good practice to post also a link to the product page or the manual.
There are 2 "240" bars:
http://proxdirect.com/products/view/240BAR-RGB-LEDs-Bar-Wash-Fixture-X-240BAR-RGB-IRC
http://proxdirect.com/products/view/240BAR-RGBA-LEDs-Bar-Wash-Fixture-X-240BAR-RGBA-IRC
I suppose it's the RGB version, but it's better to specify it in the product model name
3- modes 2,3,4,7 should not have a head (cause they implicitely have a single head)

**Comment by nedmech** [comment]
Thanks Massimo.  I'll make the changes to the fixture this evening when I'm home from work.

I'm still getting used to the Git workflow.  I hadn't intended the RGB Script to get included in this pull request.  Based on what happened this time, I'm assuming I should create new branches in my fork for things I want to create separate pull requests for.  Is that the correct way to handle it?

**Comment by mcallegari** [comment]
No problem.
I don't know which GIT client you use, but you should be able to commit only the files you want to be included in the PR.
Then you come here on GitHub and create the PR.
(I'm not a GIT expert either...)

**Comment by mcallegari** [comment]
Thanks Nathan :+1: 

The RGB script looked good to me (great job !). If you have no more changes to do on it, please feel free to send another PR

**Pull request merged**
