### PR TITLE
Add fixtures

### PR DESCRIPTION
**Pull request by dadoonet**
* Laser: Ghost Green 30mw
* Laser: Kool Light 3D RGB
* Fog machine: Mac Mah Mac FOG

### CODE REVIEW

**Comment by dadoonet** [comment]
Wondering if I need to update also `FixturesMap.xml`?

**Comment by dadoonet** [comment]
I added a commit for `FixturesMap.xml`.

**Comment by mcallegari** [comment]
Hi, thanks, but all your fixtures are missing the physical information. They are important for the 2D (and later on 3D) preview.
Can you please fill them in ? If you can, please include the X (Pan) / Y (Tilt) degrees for the lasers.

Also:
- a "Mode" channel should be type "Maintenance" or "Effect", not "Intensity"
- a "Zoom" channel should have type "Beam"
- mode names should be "4 Channel" and not "4CH"

Thanks

**Comment by mcallegari** [comment]
@dadoonet ping ?

**Comment by dadoonet** [comment]
Updated, rebased and squashed.

HTH

**Comment by mcallegari** [comment]
Awsome ! Thank you very much :+1:

**Pull request merged**
