### PR TITLE
Add new fixtures

### PR DESCRIPTION
**Pull request by Virusmater**
American DJ Par Z4
OXO ColorBeam 7 FCW IR
Pro Lights Pixie Spot
beamZ SB400

### CODE REVIEW

**Comment by yestalgia** [comment]
Thanks for contributing your fixtures but there are some problems. Especially with the addition of the 3D visualiser in V5, it's important to make sure all the physical dimensions are available. 

Before submitting any fixtures for review, please run them through our online validator: https://www.qlcplus.org/fixture_validator.php

image

**Comment by Virusmater** [comment]
Sure, done!

**Comment by yestalgia** [comment]
Nice thanks for responding so quickly!

Last little bits of feedback:

OXO
- Maybe change the mode names to "DMX Mode 1," "DMX Mode 2" etc.

BeamZ:
- @mcallegari we need to decide if LED Blinder fixtures are "Colour Changers" or "Strobes" - the SB200 already in the library reports to be a Colour Changer. My personal belief is that we should consider these fixtures as strobes per @Virusmater or create another fixture type for "Blinder"
- Consider the StrobeSlowToFast preset for the "strobe" function on channel 2


Manuals for when Massimo reviews:

- ADJ: https://d295jznhem2tn9.cloudfront.net/ItemRelatedFiles/8847/par_z4.pdf
- OXO ColorBeam 7: https://www.dimmer.fr/wp-content/uploads/2017/04/OXOCOLORBEAM7_FCW.pdf
- Beamz SB400: https://www.beamzlighting.com/wp-content/uploads/2024/03/150.450-SB400-Stage-Blinder-V1.3.pdf

**Comment by Virusmater** [comment]
> Maybe change the mode names to "DMX Mode 1," "DMX Mode 2" etc.
I prefer to see the number of channels behind the mode immediately. This is the way it is in our professional equipment - Avolites Titan. If this is a big issue - let me know, I can change it.

> We need to decide if LED Blinder fixtures are "Colour Changers" or "Strobes"
SB400 doesn't change color, so would be weird to name it Color Changer. Would be nice to have "Strobes" as subcategory.

> Consider the StrobeSlowToFast preset for the "strobe" function on channel 2
Done

**Comment by yestalgia** [comment]
> I prefer to see the number of channels behind the mode immediately. This is the way it is in our professional equipment - Avolites Titan. If this is a big issue - let me know, I can change it.

I was just going off the manual but no stress.

> Would be nice to have "Strobes" as subcategory.
That suits me, whatever is decided I can update on the other fixture.

**Comment by mcallegari** [comment]
Merging but not happy about it.
Next time please use the forums like everybody else.
Will follow a commit to fix this.

**Pull request merged**
