### PR TITLE
[QLC+ 5] Russian translation

### PR DESCRIPTION
**Pull request by sanygus**
created Russian translation QLC + 5 (in the qmlui folder)

### CODE REVIEW

**Comment by mcallegari** [comment]
@sanygus excellent! Thank you a lot!
Since I am aware there are people not only in Russia that speak the Russian language, would you say the following flag is OK to make everyone happy ?
https://en.wikipedia.org/wiki/Flag_of_Russia#/media/File:Flag_of_Russia.svg

**Comment by sanygus** [comment]
Of course, it's OK!

**Comment by mcallegari** [comment]
Great!
Last thing: I need your name to give you credits for this work (website, changelog, contributors)
Obviously if you want to!

**Comment by sanygus** [comment]
My name Aleksandr Gusarov.
Thank you a lot!

**Comment by mcallegari** [comment]
Thank YOU :+1:

**Comment by sanygus** [comment]
Thanks for the great software!

**Comment by sanygus** [comment]
How soon will a stable version QLC5+ be released?
If it takes more than a year, maybe I can help with the Russain translation of the current (4) stable version?

**Comment by mcallegari** [comment]
Well, I don't have a crystall ball, but I'd really hope to enter the beta stage of QLC+ 5 in less than a year.
Final release, I'm afraid more than a year :disappointed: 
However, I'm pretty sure QLC+ 4 will be used for more than a year from now!
So your contribution with a Russian translation would be more than welcome!

**Comment by sanygus** [comment]
OK! I'll think it over.

**Comment by mcallegari** [comment]
Great!
Meantime, I've already integrated your translation into QLC+ 5!
If you are able to build from sources, please check it out, otherwise if you tell me your preferred Os, I can build a version and share it somewhere

**Comment by sanygus** [comment]
Great!
Yes, I will try to build from source. If fail, I will inform.

**Comment by sanygus** [comment]
Please help me build QLC+ 5 for Debian 9 (or build for me).
I get an error when building
`fixturemanager.cpp: In member function ‘QDir FixtureManager::systemColorFiltersDirectory()’:
fixturemanager.cpp:1322:45: error: ‘COLORFILTERSDIR’ was not declared in this scope
     return QLCFile::systemDirectory(QString(COLORFILTERSDIR), QString(KExtColorFilters));
                                             ^~~~~~~~~~~~~~~
fixturemanager.cpp: In member function ‘QDir FixtureManager::userColorFiltersDirectory()’:
fixturemanager.cpp:1327:43: error: ‘USERCOLORFILTERSDIR’ was not declared in this scope
     return QLCFile::userDirectory(QString(USERCOLORFILTERSDIR), QString(COLORFILTERSDIR),
                                           ^~~~~~~~~~~~~~~~~~~
fixturemanager.cpp:1327:73: error: ‘COLORFILTERSDIR’ was not declared in this scope
     return QLCFile::userDirectory(QString(USERCOLORFILTERSDIR), QString(COLORFILTERSDIR),
                                                                         ^~~~~~~~~~~~~~~
make[1]: *** [Makefile:10296: fixturemanager.o] Ошибка 1
`

QMake version 3.1
Using Qt version 5.10.1
GNU Make 4.2.1

**Comment by mcallegari** [comment]
That's usually an error that happens on a "dirty build".
You probably built QLC+ 4 before, so to switch to QLC+ 5, you need to do `make distclean` first.
Then `qmake CONFIG+=qmlui` and make

**Comment by sanygus** [comment]
Thanks!
It worked! The build was successful!

**Pull request merged**
