### PR TITLE
add FOS Technologies Fixtures

### PR DESCRIPTION
**Pull request by ginopc**
Add follows Fixtures
1. FOS IQ Par
2. FOS IQ28x12 Wash
3. FOS Iridium 75W Spot

### CODE REVIEW

**Comment by mcallegari** [comment]
Hi

1. a link to product manuals or manufacturer website wouldn't have wasted...
2. have you actually tried this PR in your environment? The folder "FosTechnologies" will not work with "FOS Technologies" (written inside definitions with a space). The correct folder name should be "FOS_Technologies" with the underscore
3. Do these pass the online fixture validator?
4. I found typos
5. Lot of capability presets are missing, like shutter properties and colors

This is why it is suggested to submit definition via forum threads.

**Comment by mcallegari** [comment]
@ginopc do you intend to fix this PR or is this abandoned?

**Comment by ginopc** [comment]
> 5\. ot of capability prese

Sorry. I see it now
Thank for feedback

**Comment by ginopc** [comment]
Fixed issues and renamed folder name on Fixtures

**Comment by mcallegari** [comment]
OK, thanks
I'll merge and add myself what is missing

**Pull request merged**
