### PR TITLE
Build option+ui fix

### PR DESCRIPTION
**Pull request by Ledjlale**
Add a compile option to build for QLC5.
Remove qml slot depreciation.
Adapt disclaimer text size to content.

### CODE REVIEW

**Comment by mcallegari** [comment]
@Ledjlale thanks for splitting the PRs.
What about the cmake option? I see there is already a message printed when building with qmlui=ON
https://github.com/mcallegari/qlcplus/blob/master/CMakeLists.txt#L77

Furthermore, the documentation says the default value for boolean is OFF anyway
https://cmake.org/cmake/help/latest/command/option.html

Can you help me understand that change? thanks

**Comment by Ledjlale** [comment]
The option keyword allows the IDE to know what variable to propose to the user.
For instance, I'm using QtCreator and without it, the variable is not shown in the configuration : we have to enter it manually. That means that we have to be aware of this variable outside of the configuration.

A more simple example : run cmake-gui and configure the project. The variable qmlui doesn't appear.
But if you add this option() line, you will get your variable in the configuration. Then, you don't need an external documentation/check the code for this ;)

**Comment by Ledjlale** [comment]
By the way, maybe we could rename the variable to a QLC_5_BUILD or something more clear?

**Comment by mcallegari** [comment]
> (and I almost post the question about how to build QLC5 on the forum, before checking the code.. so having this kind of options could save some bile :p)

Well, instructions were in the wiki actually... :wink: 
https://github.com/mcallegari/qlcplus/wiki/QLC-Plus-5-build-HOWTO

I agree to have the variable at hand, but please let's keep it "qmlui" for now. In the end v5 is the v4 engine+plugins built with a QML UI.

Please fix this build by updating the ICU version on windows, like this:
https://github.com/mcallegari/qlcplus/commit/4eaa31033687432359585d3294d7d789dc92b125

Thanks

**Comment by Ledjlale** [comment]
The branch was just not rebased from the rebased [callegari:qmltoqt6](https://github.com/mcallegari/qlcplus/tree/qmltoqt6) ^^  
Or I didn't understand your request. The ICU is 75

**Comment by mcallegari** [comment]
> The branch was just not rebased from the rebased [callegari:qmltoqt6](https://github.com/mcallegari/qlcplus/tree/qmltoqt6) ^^

Ok, it was probably this.
Merged then, thanks :+1:

**Pull request merged**
