### PR TITLE
New Fixture - American DJ Hyper Gem LED

### PR DESCRIPTION
**Pull request by boxy321**
Link to post and datasheet:

http://www.qlcplus.org/forum/viewtopic.php?f=6&t=8956

### CODE REVIEW

**Comment by mcallegari** [comment]
@boxy321 Uhm...added and the deleted ?

**Comment by boxy321** [comment]
Yes. Forgot the heads.


Sent from my Samsung device

-------- Original message --------

**Comment by mcallegari** [comment]
@boxy321 As I suspected, this PR added the fixture and then deleted it, so the file is not actually upstream.
Can you please re-submit the correct one ?

**Comment by boxy321** [comment]
I missed the heads off so resubmitted it.


Sent from my Samsung device

-------- Original message --------

**Comment by mcallegari** [comment]
@boxy321 sorry I don't understand. Where have you resubmitted the file ? Not here

**Comment by boxy321** [comment]
Hmm. Will resubmit on Monday. No problem.


Sent from my Samsung device

-------- Original message --------

**Pull request merged**
