### PR TITLE
New fixture - Blizzard Lighting HotBox Infiniwhite

### PR DESCRIPTION
**Pull request by boxy321**
Created here:

http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8950

Added physical data and small corrections.

### CODE REVIEW

**Comment by boxy321** [comment]
Hmm. It seems to have merged all the commits into one pull request even though I have submitted them individually. Don't know how it does that.

Just remembered. I forgot to create a separate branch for each one! It won't happen again.

**Comment by mcallegari** [comment]
@boxy321 should be fine. Is the Chauvet fixture OK as well ?
Looks good to me.

**Comment by boxy321** [comment]
All good. Usual physical bits missing and multi-function channels incorrect.


Sent from my Samsung device

-------- Original message --------

**Comment by mcallegari** [comment]
Merged, thanks.
Please try to keep fixtures separated.

**Pull request merged**
