### PR TITLE
Re-Enable CAPS check in fixtureeditor and update other RexExp patterns

### PR DESCRIPTION
**Pull request by hjtappe**
Related to https://github.com/mcallegari/qlcplus/issues/1329.

Documentation
https://doc.qt.io/qt-5/qregularexpression.html#introduction

### CODE REVIEW

**Comment by hjtappe** [comment]
Do I interpret the build correctly that the fixture editor is not currently built on Travis CI? I would expect a QT='qt5' build for the fixtureeditor directory which is not built in companion with the top-level build. Should I try to add it or is it not available intentionally?

**Comment by hjtappe** [comment]
Can you please take a look into the build configurations? The Appveyor build fails on some missing clang32 database and the Travis build fails on the installation on installing the required ppa.

**Comment by mcallegari** [comment]
Hi, thanks for this patch.
Appveyor should be fixed now and Travis is failing because of unstable PPA. Sometimes it works, sometimes it doesn't. I hope they'll fix it.

**Comment by mcallegari** [comment]
Thanks a lot! 👍

**Pull request merged**
